# Prerrequisitos: Teoría de conjuntos y combinatoria

Para aprender cálculo de probabilidades son necesarios conocimientos de:

1. Cálculo: derivadas, integrales, límites, sumas de series...
2. Geometría básica y Álgebra Lineal : rectas, hiperplanos, volúmenes... Matrices, valores propios...
3. Teoría de Conjuntos y Combinatoria.

Por experiencia sabemos que  la mayoría de estudiantes tienen más conocimientos de  Cálculo, Geometría y Matrices. Sin embargo, muchos tienen  una falta de conocimientos  en Teoría básica de Conjuntos y Combinatoria (Matemática Discreta).


##  Teoría de conjuntos

<l class = "definition"> **Definición de conjunto** </l>

La definición de conjunto es una [idea o noción primitiva](https://es.wikipedia.org/wiki/Concepto_primitivo). Es decir, es una idea básica del pensamiento humano: un conjunto es una colección de objetos (números, imágenes, jugadores de fútbol, palabras, colores...).


La Teoría de Conjuntos básica es simple y natural y es la que necesitamos para este curso. Por otro lado, la Teoría de Conjuntos matemática es más compleja y presenta varias paradojas como la [paradoja de Russell](https://es.wikipedia.org/wiki/Paradoja_de_Russell).


La idea o noción práctica de conjunto es la de una  colección de objetos de un cierto tipo.

Estas colecciones o  conjuntos se pueden definir por:

* Compresión: reuniendo los objetos que cumplen una propiedad $p$
* Extensión:  dando una lista exhaustiva de  los miembros del conjunto



###  Conjuntos básicos

Los  conjuntos suelen tener un conjunto madre como por ejemplo 

* $\mathbb{N}=\{0,1,2,\ldots\}$; los números naturales.
* $\mathbb{Z}=\{\ldots,-2,-1,0,1,2,\ldots\}$; los números enteros.
* $\mathbb{Q}=\left\{\frac{p}{q}\ \Big|\ p,q\in \mathbb{Z} \mbox{ y } q \not= 0\right\}$; los números racionales.
* $\mathbb{R}=\{\mbox{Todos los puntos de una recta}\}$; los números reales.
* $\mathbb{C}= \left\{a+b\cdot i\  \big|\  a,b\in \mathbb{R}\right\}$; los números complejos.
* Alfabeto = $\{a,b,c,\ldots, A,B,C,\ldots\}$
* Palabras = $\{paz, guerra, amor, probabilidad,\ldots\}$

Recordemos que $i$ es la unidad imaginaria que satisface $i = +\sqrt{-1}$.



