project:
  type: book
  output-dir: docs
  

book:
  title: "Análisis de datos (Grado de Matemáticas UIB)"
  author: "Irene García, Ricardo Alberich, Arnau Mir y Francesc Roselló"
  date: "9/18/2023"
  reader-mode: true
  
  page-footer:
    left: |
      Análisis de Datos UIB
    right: |
     Este libro se ha creado con  <a href="https://quarto.org/">Quarto</a>.
  cover-image: atlas.jpeg
  favicon: atlas.jpeg
  site-url: https://aprender-uib.github.io/AD
  repo-url: https://github.com/AprendeR-UIB/AD/Enlaces
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd
    
    

bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: es 
  pdf:
    documentclass: scrreprt
    linkcolor: blue
    lang: es 



