project:
  type: book
  output-dir: docs
  

book:
  title: "Notas de clase para Análisis de datos"
  author: "Irene García, Ricardo Alberich, Arnau Mir y Francesc Roselló"
  date: "2023"
  reader-mode: true
  
  page-footer:
    left: |
      Introducción a la probabilidad para el análisis de datos: Con R y python.
    right: |
     Este libro se ha creado con  <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.jpg
  favicon: cover.jpg
  site-url: https://github.com/RicUIB/Enlaces
  repo-url: https://github.com/RicUIB/Enlaces
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - intro.qmd
    - references.qmd
    
    

bibliography: references.bib

format:
  html:
    theme: cosmo
    lang: es 
  pdf:
    documentclass: scrreprt
    linkcolor: blue
    lang: es 



