<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Análisis de datos - 4&nbsp; Análisis de Componentes Principales</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./references.html" rel="next">
<link href="./Inferencia.html" rel="prev">
<link href="./atlas.jpeg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./ACP.html"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Análisis de Componentes Principales</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Análisis de datos</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/AprendeR-UIB/AD/Enlaces" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Alternar modo lector">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción al Análisis de Datos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./EM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Análisis Multivariante</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Inferencia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Inferencia multivariante en poblaciones normales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ACP.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Análisis de Componentes Principales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#introducción" id="toc-introducción" class="nav-link active" data-scroll-target="#introducción"><span class="header-section-number">4.1</span> Introducción</a>
  <ul class="collapse">
  <li><a href="#matriz-tabla-de-datos" id="toc-matriz-tabla-de-datos" class="nav-link" data-scroll-target="#matriz-tabla-de-datos"><span class="header-section-number">4.1.1</span> Matriz (tabla) de datos</a></li>
  <li><a href="#enfoque-geométrico" id="toc-enfoque-geométrico" class="nav-link" data-scroll-target="#enfoque-geométrico"><span class="header-section-number">4.1.2</span> Enfoque geométrico</a></li>
  </ul></li>
  <li><a href="#cálculo-de-las-componentes" id="toc-cálculo-de-las-componentes" class="nav-link" data-scroll-target="#cálculo-de-las-componentes"><span class="header-section-number">4.2</span> Cálculo de las componentes</a>
  <ul class="collapse">
  <li><a href="#cálculo-de-la-primera-componente" id="toc-cálculo-de-la-primera-componente" class="nav-link" data-scroll-target="#cálculo-de-la-primera-componente"><span class="header-section-number">4.2.1</span> Cálculo de la primera componente</a></li>
  <li><a href="#cálculo-de-la-segunda-componente" id="toc-cálculo-de-la-segunda-componente" class="nav-link" data-scroll-target="#cálculo-de-la-segunda-componente"><span class="header-section-number">4.2.2</span> Cálculo de la segunda componente</a></li>
  <li><a href="#generalización" id="toc-generalización" class="nav-link" data-scroll-target="#generalización"><span class="header-section-number">4.2.3</span> Generalización</a></li>
  </ul></li>
  <li><a href="#ejemplo" id="toc-ejemplo" class="nav-link" data-scroll-target="#ejemplo"><span class="header-section-number">4.3</span> Ejemplo</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/AprendeR-UIB/AD/Enlaces/edit/main/ACP.qmd" class="toc-action">Editar esta página</a></p><p><a href="https://github.com/AprendeR-UIB/AD/Enlaces/issues/new" class="toc-action">Informar de un problema</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Análisis de Componentes Principales</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introducción" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="introducción"><span class="header-section-number">4.1</span> Introducción</h2>
<p>Cuando nos enfrentamos a problemas que se desarrollan en espacios muestrales de altas dimensiones, puede interesar considerar el estudio de dichos problemas en espacios de menor dimensión.</p>
<p>El análisis de componentes principales, PCA por sus siglas en inglés (<strong>P</strong>rincipal <strong>C</strong>omponent <strong>A</strong>nalysis), es uno de los métodos más populares del análisis multivariado.</p>
<p>El PCA se utiliza cuando deseamos obtener una representación en menor dimensión para un conjunto de variables cuantitativas correlacionadas y queremos expresar la información importante como un conjunto de pocas variables nuevas llamadas <strong>componentes principales</strong>. Estas componentes se corresponden con una combinación lineal de las variables originales.</p>
<p>Dado que la información de un conjunto de datos se corresponde a la variación total que contiene, el objetivo del PCA es identificar direcciones (o componentes principales) a lo largo de las cuales la variación en los datos es máxima.</p>
<p>La <strong>reducción de la dimensionalidad</strong> consiste en describir con cierta precisión los valores de las <span class="math inline">\(p\)</span> variables por un pequeño subconjunto <span class="math inline">\(r&lt;p\)</span> de ellas con una pérdida mínima de información. Por lo tanto, proyectaremos la muestra original en el nuevo subespacio pero conservando algunas características. En particular, vamos a realizar un ajuste ortogonal por mínimos cuadrados.</p>
<p>Algunos ámbitos importantes en los que es frecuente la utilización de la Reducción de la dimensionalidad podrían ser:</p>
<ul>
<li><strong>Reconocimiento facial</strong>: Al partir de una proyección facial de tamaño <span class="math inline">\(M \times N\)</span> píxeles puede resultar complicado el estudio completo de dicha imagen, puesto que da lugar a un vector con dimensión excesivamente alta. De modo que debemos reducir la dimensionalidad pero de forma que nos permita generar un sistema de clasificación facial de un individuo entre el resto de la población.</li>
</ul>
<p><br></p>
<ul>
<li><strong>Modelización de secuencias genómicas</strong>: Considera una proteína, formada por una secuencia de aminoácidos donde es posible encontrar hasta 20 tipos diferentes, su longitud puede llegar a ser de decenas hasta cientos de decenas de aminoácidos. De modo que, las proteínas con igual estructura pueden ser agrupadas en familias y el conjunto de familias proteicas distintas tendrá una dimensión inferior al conjunto de todas las proteínas. Pudiendo así encontrar de forma menos compleja propiedades particulares o incluso identificar nuevos miembros de una familia.</li>
</ul>
<section id="matriz-tabla-de-datos" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="matriz-tabla-de-datos"><span class="header-section-number">4.1.1</span> Matriz (tabla) de datos</h3>
<p>Supongamos que disponemos de una tabla de datos con los valores de <span class="math inline">\(p\)</span>-variables en <span class="math inline">\(n\)</span> elementos de una población arreglados en una matriz <span class="math inline">\(\mathbf{X}\)</span> de la siguiente forma:</p>
<table class="table">
<colgroup>
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">ID</th>
<th style="text-align: center;"><span class="math inline">\(\bf{x}_1\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\bf{x}_2\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\ldots\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\bf{x}_p\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\bf{v}_1\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\bf{v}_2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(1\)</span></td>
<td style="text-align: center;"><span class="math inline">\(x_{11}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(x_{12}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\ldots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(x_{1p}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(v_{11}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(v_{12}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(2\)</span></td>
<td style="text-align: center;"><span class="math inline">\(x_{21}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(x_{22}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\ldots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(x_{2p}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(v_{21}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(v_{22}\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(3\)</span></td>
<td style="text-align: center;"><span class="math inline">\(x_{31}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(x_{32}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\ldots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(x_{3p}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(v_{31}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(v_{32}\)</span></td>
</tr>
<tr class="even">
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\ddots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\vdots\)</span></td>
</tr>
<tr class="odd">
<td style="text-align: center;"><span class="math inline">\(n\)</span></td>
<td style="text-align: center;"><span class="math inline">\(x_{n1}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(x_{n2}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(\ldots\)</span></td>
<td style="text-align: center;"><span class="math inline">\(x_{np}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(v_{n1}\)</span></td>
<td style="text-align: center;"><span class="math inline">\(v_{n2}\)</span></td>
</tr>
</tbody>
</table>
<ul>
<li><p>Donde las variables <span class="math inline">\(x_1,\ldots, x_n\)</span> describen a los <span class="math inline">\(n\)</span> individuos observados.</p></li>
<li><p>Las variables <span class="math inline">\(v_1\)</span>, <span class="math inline">\(v_2\)</span> son de perfil (o explicativas) y ayudan a interpretar la variabilidad de los datos.</p></li>
</ul>
<p>El objetivo del análisis es la <strong>reducción de la dimensionalidad</strong>. Buscamos un <strong>espacio de variables más reducido y fácil de interpretar</strong>.</p>
<p>El problema es que si reducimos el número de variables es posible que “perdamos parte toda la variabilidad de los datos originales”.</p>
<p>Así la idea básica es consentir una pérdida de información para lograr una ganancia en la significación.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/acp_1.PNG" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<!-- ## Análisis Factorial -->
<!-- * Algunos autores consideran el ACP como una parte del Análisis Factorial. -->
<!-- * En las técnicas de Análisi Factorialse postula que **la variabilidad total** se puede explicar mediante distintos tipos de factores: -->
<!--  * ["factores comunes"]{style="color: blue;"} subyacentes: $F_i$. -->
<!--  * ["factores específicos"]{style="color: blue;"} de las variables: $E_i$. -->
<!--  * ["Error o fluctuaciones aleatorias"]{style="color: blue;"}: $A_i$. -->
<!-- $$X_1=\alpha_{1 1} F_1+ \alpha_{1 2} F_2+\cdots +\alpha_{1 k} F_k+ E_1+ A_1$$ -->
<!-- $$X_2=\alpha_{2 1} F_1+ \alpha_{2 2} F_2+\cdots +\alpha_{2 k} F_k+ E_2+ A_2$$ -->
<!-- $$\vdots \; \; \; \; \; \; \; \; \vdots \; \; \; \; \; \; \; \; \vdots $$ -->
<!-- $$X_p=\alpha_{p 1} F_1+ \alpha_{p 2} F_2+\cdots +\alpha_{p k} F_k+ E_p+ A_p$$ -->
<!-- * Podríamos decir que en un **Análisis Factorial se fija a priori la -->
<!-- cantidad de varianza de cada variable que debe quedar interpretada por los factores comunes**.  -->
<!-- * Este valor recibe el nombre de **comunalidad** y se suele representar como $h_i^2$. -->
<!-- Utilizaremos la siguiente notación: -->
<!-- * La comunalidad $h_i^2$, de la variable $X_i$,  es la varianza explicada por $F_1,F_2,\ldots F_k.$ -->
<!-- *  La diferencia $s_i^2-h_i^2$  es la varianza  de la variable  $X_i$    que  explican los factores específicos y aleatorios. -->
<!-- <br> -->
<!-- $$\color{red}{\mbox{Var. observada = Var. común + Var. específica y aleatorios}}.$$ -->
<!-- Todos los factores son comunes: -->
<!-- $$X_1=\alpha_{1 1} CP_1+ \alpha_{1 2} CP_2+\cdots +\alpha_{1 p} CP_p$$ -->
<!-- $$X_2=\alpha_{2 1} CP_1+ \alpha_{2 2} CP_2+\cdots +\alpha_{2 p} CP_p$$ -->
<!-- $$\vdots \; \; \; \; \; \; \; \; \vdots \; \; \; \; \; \; \; \; \vdots $$ -->
<!-- $$X_p=\alpha_{p 1} CP_1+ \alpha_{p 2} CP_2+\cdots +\alpha_{p p} CP_p$$ -->
<p><br> <br> <!-- Se trata de encontrar unas nuevas variables $CP_1,\ldots CP_p$, a las que --> <!-- llamaremos --> <!-- componentes principales, de forma que: --></p>
<!-- * Se cumplan las condiciones anteriores. -->
<!-- * El origen de las variables esté situado en el vector de medias o centro de gravedad de las observaciones. -->
<!-- * Sean incorreladas entre si, es decir,  $Cor(CP_i,CP_j)=0$ para $i=j, \;\; i,j=1\ldots,p$. -->
<!-- * Se cumple que $Var(CP_1)\geq Var(CP_2)\geq\cdots\geq Var(CP_p)$ y estas varianzas sean máximas. -->
<!-- * Se conserva la varianza total (inercia) de la nube de puntos. -->
<!-- ```{r echo=FALSE, out.width = "40%",fig.align='center'} -->
<!-- knitr::include_graphics("Figuras/acp_2.PNG") -->
<!-- ``` -->
</section>
<section id="enfoque-geométrico" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="enfoque-geométrico"><span class="header-section-number">4.1.2</span> Enfoque geométrico</h3>
<!-- * **Sobre los datos centrados**: A cada variable se le resta su media -->
<!-- $x_i-\overline{x}_i$; de modo que las variables centradas tienen media cero y la misma varianza que las variables originales. Se le suele llamar **ACP de covarianzas**.    -->
<!-- * **Sobre los datos tipificados**:  $\frac{x_{i}-\overline{x}_i}{s_i}$. Las variables tipificadas tienen media cero y varianza 1.  Se le suele llamar **ACP de correlaciones o normado**. -->
<!-- Dada una matriz de datos $\mathbf{X}_{n\times p}$, denotemos por $\tilde{\mathbf{X}}$ la matriz de datos centrada. Recordad que:  -->
<!-- * El estimador sesgado de la matriz de covarianzas de $\mathbf{X}$ viene dada por  -->
<!-- $$\mathbf{S}=1/n \; \tilde{\mathbf{X}}^t\tilde{\mathbf{X}}$$  -->
<!-- * Si llamamos $\mathbf{Z}$ a la tabla de los datos tipificados, la matriz de correlaciones viene dada por:  -->
<!-- $$\mathbf{R}=1/n \; \mathbf{Z}^t\mathbf{Z}$$  -->
<!-- **Propiedades** -->
<!-- * Los **componentes principales vienen determinadas por los vectores propios ortonormales** -->
<!-- (ordenados de mayor a menor valor propio) de la matriz de covarianzas (para datos centrados) y de la matriz de correlaciones (para los datos tipificados). -->
<!-- * Así en el ACP de covarianzas cada variable interviene con su propia -->
<!-- varianza mientras que el ACP de correlaciones todas las variables tienen varianza 1. -->
<!-- **Interpretación geométrica** -->
<p>Supongamos que <span class="math inline">\(p=2\)</span> y que la nube de puntos de nuestra matriz de datos es la de la siguiente figura:</p>
<div class="cell" data-layout-align="center" data-fig="true">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ACP_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>La siguiente figura muestra las dos <strong>componentes principales</strong>, es decir, las direcciones de las proyecciones que tienen máxima variabilidad.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/eje_CP.PNG" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Si proyectamos en la dirección de la <strong>primera componente</strong> obtendremos las proyecciones siguientes (en color azul):</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/eje_CP_2.PNG" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><br><br></p>
<p>Lo que significa que la varianza de los puntos azules es máxima; en el sentido de que cualquier otra dirección o recta, las proyecciones sobre ésta tendrán a lo más igual varianza.</p>
<p>Los puntos azules representan las coordenadas que tienen los puntos de nuestra tabla de datos (centrada) tomando como eje de abcisas la <strong>primera componente</strong> <span class="math inline">\(CP_1\)</span>.</p>
<p>Si proyectamos en la dirección de la <strong>“segunda componente”</strong>, obtendremos las proyecciones siguientes (en color verde):</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/eje_CP_3.PNG" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="cálculo-de-las-componentes" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="cálculo-de-las-componentes"><span class="header-section-number">4.2</span> Cálculo de las componentes</h2>
<section id="cálculo-de-la-primera-componente" class="level3" data-number="4.2.1">
<h3 data-number="4.2.1" class="anchored" data-anchor-id="cálculo-de-la-primera-componente"><span class="header-section-number">4.2.1</span> Cálculo de la primera componente</h3>
<p>La primera componente principal se define como la combinación lineal de las variables originales que tiene varianza máxima. Los valores en esta primera componente de los <span class="math inline">\(n\)</span> individuos se representarán por un vector <span class="math inline">\(\mathbf{z_1}\)</span> dado por <span class="math display">\[\mathbf{z_1}=\mathbf{Xa_1}.\]</span> Si las variables originales tienen media cero, <span class="math inline">\(\mathbf{z_1}\)</span> también tendrá media nula. Su varianza será</p>
<p><span class="math display">\[\begin{equation} \tag{1}
Var(\mathbf{z_1})=\frac{1}{n}\mathbf{z_1^t}\mathbf{z_1}=\frac{1}{n}\mathbf{a_1^t X^t}\mathbf{Xa_1}=\mathbf{a_1^t S}\mathbf{a_1}
\end{equation}\]</span></p>
<p>donde <span class="math inline">\(\mathbf{S}\)</span> es la matriz de varianzas-covarianzas de las observaciones.</p>
<p>Es obvio que podemos maximizar la varianza tanto como queramos aumentando el módulo del vector <span class="math inline">\(\mathbf{a_1}\)</span>. Para que maximizar (1) tenga solución debemos imponer una restricción al módulo del vector <span class="math inline">\(\mathbf{a_1}\)</span>, y, sin pérdida de generalidad, impondremos que <span class="math inline">\(\mathbf{a_1^t}\mathbf{a_1}=1\)</span>. Introducimos esta restricción mediante el multiplicador de Lagrange: <span class="math display">\[M=\mathbf{a_1^t}S\mathbf{a_1}-\lambda(\mathbf{a_1^t}\mathbf{a_1}-1)\]</span> y maximizamos esta expresión derivando respecto a las componentes de <span class="math inline">\(\mathbf{a_1}\)</span> e igualando a cero. Entonces <span class="math display">\[\frac{\partial M}{\partial \mathbf{a_1}}=2\mathbf{Sa_1}-2 \lambda \mathbf{a_1}=0,\]</span></p>
<p>cuya solución es:</p>
<p><span class="math display">\[\begin{equation} \tag{2}
\mathbf{Sa_1}= \lambda \mathbf{a_1},
\end{equation}\]</span></p>
<p>que implica que <span class="math inline">\(\mathbf{a_1}\)</span> es un vector propio de la matriz <span class="math inline">\(\mathbf{S}\)</span>, y <span class="math inline">\(\lambda\)</span> su correspondiente valor propio.</p>
<p>Para determinar qué valor propio de <span class="math inline">\(\mathbf{S}\)</span> es la solución de (2), multiplicamos por la izquierda por <span class="math inline">\(\mathbf{a_1^t}\)</span> a esta ecuación,</p>
<p><span class="math display">\[\begin{equation}
\mathbf{a_1^t S a_1}= \lambda \mathbf{a_1^t a_1}= \lambda
\end{equation}\]</span></p>
<p>y concluimos, por (1) que <span class="math inline">\(\lambda\)</span> es la varianza de <span class="math inline">\(\mathbf{z_1}\)</span>. Como esta es la cantidad que queremos maximizar, <span class="math inline">\(\lambda\)</span> será el mayor valor propio de la matriz <span class="math inline">\(\mathbf{S}\)</span>. Su vector asociado, <span class="math inline">\(\mathbf{a_1}\)</span>, define los coeficientes de cada variable en la primera componente principal.</p>
<p><span style="color: red;"><em>Ejercicio:</em></span> Calcula la primera componente principal con los logaritmos del fichero <code>acciones.txt</code> que podéis descargad en Aula Digital. Las observaciones corresponden a distintas acciones que cotizan en el mercado español y las variables son:</p>
<ul>
<li><code>V1</code> la rentabilidad efectiva por dividendos,</li>
<li><code>V2</code> la proporción de beneficios que va a dividendos</li>
<li><code>V3</code> el ratio entre precio por acción y beneficios.</li>
</ul>
<p>¿Cuál de las variables está mejor representada por la componente principal 1?</p>
</section>
<section id="cálculo-de-la-segunda-componente" class="level3" data-number="4.2.2">
<h3 data-number="4.2.2" class="anchored" data-anchor-id="cálculo-de-la-segunda-componente"><span class="header-section-number">4.2.2</span> Cálculo de la segunda componente</h3>
<p>Vamos a obtener el mejor plano de proyección de l matriz <span class="math inline">\(\mathbf{X}\)</span>. Lo calcularemos estableciendo como función objetivo que la suma de las varianzas de <span class="math inline">\(\mathbf{z_1}=\mathbf{Xa_1}\)</span> y <span class="math inline">\(\mathbf{z_2}=\mathbf{Xa_2}\)</span> sean máximas, donde <span class="math inline">\(\mathbf{a_1}\)</span> y <span class="math inline">\(\mathbf{a_2}\)</span> son los vectores que definen el plano. La función objetivo será:</p>
<p><span class="math display">\[\begin{equation} \tag{3}
\phi=\mathbf{a_1^t S}\mathbf{a_1} + \mathbf{a_2^t S}\mathbf{a_2} - \lambda_1 (\mathbf{a_1^t}\mathbf{a_1}-1) - \lambda_2 (\mathbf{a_2^t}\mathbf{a_2}-1)
\end{equation}\]</span></p>
<p>que incorpora las restricciones de que las direcciones deben de tener módulo unitario. Derivando e igualando a cero: <span class="math display">\[\frac{\partial \phi}{\partial \mathbf{a_1}}=2\mathbf{Sa_1}-2 \lambda_1 \mathbf{a_1}=0\]</span></p>
<p><span class="math display">\[\frac{\partial \phi}{\partial \mathbf{a_2}}=2\mathbf{Sa_2}-2 \lambda_2 \mathbf{a_1}=0\]</span></p>
<p>La solución del sistema es: <span class="math display">\[\begin{equation} \tag{4}
\mathbf{Sa_1}= \lambda \mathbf{a_1},
\end{equation}\]</span> <span class="math display">\[\begin{equation} \tag{5}
\mathbf{Sa_2}= \lambda \mathbf{a_2},
\end{equation}\]</span></p>
<p>que indica que <span class="math inline">\(\mathbf{a_1}\)</span> y <span class="math inline">\(\mathbf{a_2}\)</span> deben ser vectores propios de <span class="math inline">\(\mathbf{S}\)</span>.</p>
<p>Tomando los vectores propios de norma uno y sustituyendo en (3), se obtiene que, en el máximo, la función objetivo es <span class="math display">\[\begin{equation} \tag{6}
\phi=\lambda_1+\lambda_2
\end{equation}\]</span></p>
<p>es claro que <span class="math inline">\(\lambda_1\)</span> y <span class="math inline">\(\lambda_2\)</span> deben ser los dos valores propios mayores de la matriz <span class="math inline">\(\mathbf{S}\)</span> y <span class="math inline">\(\mathbf{a_1}\)</span> y <span class="math inline">\(\mathbf{a_2}\)</span> sus correspondientes vectores propios.</p>
<p>Observad que la covarianza entre <span class="math inline">\(\mathbf{z_1}\)</span> y <span class="math inline">\(\mathbf{z_2}\)</span>, dada por <span class="math inline">\(\mathbf{a_1^t S a_2}\)</span> es cero ya que =0, y las variables<span class="math inline">\(\mathbf{z_1}\)</span> y <span class="math inline">\(\mathbf{z_2}\)</span> estarán incorreladas.</p>
<p>Se puede demostrarse que si en lugar de maximizar la suma de varianzas, que es la traza de la matriz de covarianzas de la proyección, se maximiza la varianza generalizada (el determinante de la matriz de covarianzas) se obtiene el mismo resultado.</p>
</section>
<section id="generalización" class="level3" data-number="4.2.3">
<h3 data-number="4.2.3" class="anchored" data-anchor-id="generalización"><span class="header-section-number">4.2.3</span> Generalización</h3>
<p>Análogamente, el espacio de dimensión <span class="math inline">\(r\)</span> que mejor representa a los puntos viene definido por los vectores propios asociados a los <span class="math inline">\(r\)</span> mayores valores propios de <span class="math inline">\(\mathbf{S}\)</span>. Estas direcciones se denominan direcciones principales de los datos y a las nuevas variables por ellas definidas componentes principales. En general, la matriz <span class="math inline">\(\mathbf{X}\)</span> (y por tanto la <span class="math inline">\(\mathbf{S}\)</span>) tiene rango <span class="math inline">\(p\)</span>, existiendo entonces tantas componentes principales como variables que se obtendrán calculando los valores propios o raíces características, <span class="math inline">\(\lambda_1, \ldots, \lambda_p\)</span>, de la matriz de varianzas y covarianzas de las variables, <span class="math inline">\(\mathbf{S}\)</span> , mediante:</p>
<p><span class="math display">\[\begin{equation} \tag{7}
|\mathbf{S}-\lambda\mathbf{I}|=0
\end{equation}\]</span></p>
<p>y sus vectores asociados son: <span class="math display">\[\begin{equation} \tag{8}
(\mathbf{S}-\lambda_i\mathbf{I})\mathbf{a_i}=0.
\end{equation}\]</span></p>
<p>Los términos <span class="math inline">\(\lambda_i\)</span> son reales, al ser la matriz <span class="math inline">\(\mathbf{S}\)</span> simétrica, y positivos, ya que <span class="math inline">\(\mathbf{S}\)</span> es definida positiva.</p>
<p>Por ser <span class="math inline">\(\mathbf{S}\)</span> simétrica si <span class="math inline">\(\lambda_j\)</span> y <span class="math inline">\(\lambda_h\)</span> son dos raíces distintas sus vectores asociados son ortogonales.</p>
<p>Si <span class="math inline">\(\mathbf{S}\)</span> fuese semidefinida positiva de rango <span class="math inline">\(r &lt; p\)</span>, lo que ocurriría si <span class="math inline">\(p−r\)</span> variables fuesen combinación lineal de las demás, habría solamente <span class="math inline">\(r\)</span> raíces características positivas y el resto serían ceros.</p>
<p>Llamando <span class="math inline">\(\mathbf{Z}\)</span> a la matriz cuyas columnas son los valores de las <span class="math inline">\(p\)</span> componentes en los <span class="math inline">\(n\)</span> individuos, estas nuevas variables están relacionadas con las originales mediante:</p>
<p><span class="math display">\[\begin{equation} \tag{9}
\mathbf{Z}=\mathbf{X}\mathbf{A}
\end{equation}\]</span></p>
<p>donde <span class="math inline">\(\mathbf{A^t A}=\mathbf{I}\)</span>. Calcular las componentes principales equivale a aplicar una transformación ortogonal <span class="math inline">\(\mathbf{A}\)</span> a las variables <span class="math inline">\(\mathbf{X}\)</span> (ejes originales) para obtener unas nuevas variables <span class="math inline">\(\mathbf{Z}\)</span> incorreladas entre sí. Esta operación puede interpretarse como elegir unos nuevos ejes coordenados, que coincidan con los “ejes naturales” de los datos.</p>
</section>
</section>
<section id="ejemplo" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="ejemplo"><span class="header-section-number">4.3</span> Ejemplo</h2>
<p>Vamos a realizar un análisis de componentes principales (PCA) sobre un conjunto de datos con la estatura de niños recién nacidos.</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;"><span class="math inline">\(\bf{x}_1\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\bf{x}_2\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\bf{x}_3\)</span></th>
<th style="text-align: center;"><span class="math inline">\(\bf{x}_4\)</span></th>
<th style="text-align: center;">Sexo</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">78</td>
<td style="text-align: center;">48.2</td>
<td style="text-align: center;">2.75</td>
<td style="text-align: center;">29.5</td>
<td style="text-align: center;">Niña</td>
</tr>
<tr class="even">
<td style="text-align: center;">69</td>
<td style="text-align: center;">45.5</td>
<td style="text-align: center;">2.15</td>
<td style="text-align: center;">26.3</td>
<td style="text-align: center;">Niña</td>
</tr>
<tr class="odd">
<td style="text-align: center;">77</td>
<td style="text-align: center;">46.3</td>
<td style="text-align: center;">4.41</td>
<td style="text-align: center;">32.2</td>
<td style="text-align: center;">Niña</td>
</tr>
<tr class="even">
<td style="text-align: center;">88</td>
<td style="text-align: center;">49</td>
<td style="text-align: center;">5.52</td>
<td style="text-align: center;">36.5</td>
<td style="text-align: center;">Niño</td>
</tr>
<tr class="odd">
<td style="text-align: center;">67</td>
<td style="text-align: center;">43</td>
<td style="text-align: center;">3.21</td>
<td style="text-align: center;">27.2</td>
<td style="text-align: center;">Niña</td>
</tr>
<tr class="even">
<td style="text-align: center;">80</td>
<td style="text-align: center;">48</td>
<td style="text-align: center;">4.32</td>
<td style="text-align: center;">27.7</td>
<td style="text-align: center;">Niña</td>
</tr>
<tr class="odd">
<td style="text-align: center;">74</td>
<td style="text-align: center;">48</td>
<td style="text-align: center;">2.31</td>
<td style="text-align: center;">28.3</td>
<td style="text-align: center;">Niña</td>
</tr>
<tr class="even">
<td style="text-align: center;">94</td>
<td style="text-align: center;">53</td>
<td style="text-align: center;">4.3</td>
<td style="text-align: center;">30.3</td>
<td style="text-align: center;">Niño</td>
</tr>
<tr class="odd">
<td style="text-align: center;">102</td>
<td style="text-align: center;">58</td>
<td style="text-align: center;">3.71</td>
<td style="text-align: center;">28.7</td>
<td style="text-align: center;">Niño</td>
</tr>
</tbody>
</table>
<p>donde:</p>
<ul>
<li><p><span class="math inline">\(\bf{x}_1:\)</span> edad en días</p></li>
<li><p><span class="math inline">\(\bf{x}_2:\)</span> estatura al nacer en cm</p></li>
<li><p><span class="math inline">\(\bf{x}_3:\)</span> peso en Kg. al nacer</p></li>
<li><p><span class="math inline">\(\bf{x}_4:\)</span> aumento porcentual de su peso con respecto de su peso al nacer.</p></li>
<li><p><strong>Sexo</strong> es una variable de perfil que podría ayudarnos a explicar algunos de los resultados del análisis de componentes principales.</p></li>
</ul>
<p>El código para la carga de datos</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">=</span> <span class="dv">9</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>p <span class="ot">=</span> <span class="dv">4</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>X <span class="ot">=</span> <span class="fu">matrix</span>(<span class="fu">c</span>(<span class="dv">78</span>,<span class="fl">48.2</span>,<span class="fl">2.75</span>,<span class="fl">29.5</span>,<span class="dv">69</span>,<span class="fl">45.5</span>,<span class="fl">2.15</span>,<span class="fl">26.3</span>,</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="dv">77</span>,<span class="fl">46.3</span>,<span class="fl">4.41</span>,<span class="fl">32.2</span>, <span class="dv">88</span>,<span class="dv">49</span>,<span class="fl">5.52</span>,<span class="fl">36.5</span>, <span class="dv">67</span>,<span class="dv">43</span>,<span class="fl">3.21</span>,<span class="fl">27.2</span>,</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="dv">80</span>,<span class="dv">48</span>,<span class="fl">4.32</span>,<span class="fl">27.7</span>, <span class="dv">74</span>,<span class="dv">48</span>,<span class="fl">2.31</span>,<span class="fl">28.3</span>, <span class="dv">94</span>,<span class="dv">53</span>,<span class="fl">4.3</span>,<span class="fl">30.3</span>,</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="dv">102</span>,<span class="dv">58</span>,<span class="fl">3.71</span>,<span class="fl">28.7</span>),<span class="at">nrow=</span>n,<span class="at">byrow=</span>T)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>Datos<span class="ot">=</span> <span class="fu">as.data.frame</span>(X)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Datos) <span class="ot">=</span> <span class="fu">paste</span>(<span class="st">"x"</span>,<span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span>p),<span class="at">sep=</span><span class="st">""</span>)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>Sexo <span class="ot">=</span> <span class="fu">as.factor</span>(<span class="fu">c</span>(<span class="st">"Niña"</span>,<span class="st">"Niña"</span>,<span class="st">"Niña"</span>,<span class="st">"Niño"</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="st">"Niña"</span>,<span class="st">"Niña"</span>,<span class="st">"Niña"</span>,<span class="st">"Niño"</span>,<span class="st">"Niño"</span>))</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>Datos<span class="sc">$</span>Sexo<span class="ot">=</span>Sexo</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><strong>Análisis exploratorio</strong></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/cor_multi.PNG" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>El código de R para realizar el cálculo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colMeans</span>(X)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 81.000000 48.777778  3.631111 29.633333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>Hn<span class="ot">=</span><span class="fu">diag</span>(n)<span class="sc">-</span><span class="dv">1</span><span class="sc">/</span>n <span class="co"># matriz de centrado</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>cX<span class="ot">=</span>Hn<span class="sc">%*%</span>X <span class="co"># matriz centrada</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(cX,<span class="dv">3</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      [,1]   [,2]   [,3]   [,4]
 [1,]   -3 -0.578 -0.881 -0.133
 [2,]  -12 -3.278 -1.481 -3.333
 [3,]   -4 -2.478  0.779  2.567
 [4,]    7  0.222  1.889  6.867
 [5,]  -14 -5.778 -0.421 -2.433
 [6,]   -1 -0.778  0.689 -1.933
 [7,]   -7 -0.778 -1.321 -1.333
 [8,]   13  4.222  0.669  0.667
 [9,]   21  9.222  0.079 -0.933</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>S<span class="ot">&lt;-</span>(<span class="dv">1</span><span class="sc">/</span>n)<span class="sc">*</span><span class="fu">t</span>(X)<span class="sc">%*%</span>Hn<span class="sc">%*%</span>X <span class="co">#estimador sesgado de la matriz de covarianza</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(S,<span class="dv">3</span>) <span class="co"># daría igual cov(X)*(n-1)/n</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        [,1]   [,2]  [,3]   [,4]
[1,] 119.333 43.133 6.148 12.511
[2,]  43.133 17.193 1.148  1.886
[3,]   6.148  1.148 1.111  2.428
[4,]  12.511  1.886 2.428  8.624</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">eigen</span>(S)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>eigen() decomposition
$values
[1] 136.61529623   8.86125966   0.73789460   0.04677667

$vectors
           [,1]        [,2]       [,3]        [,4]
[1,] 0.93439437 -0.02238785  0.2555755  0.24715806
[2,] 0.33947477  0.35413519 -0.6610845 -0.56772562
[3,] 0.04701065 -0.24770838  0.5656945 -0.78512437
[4,] 0.09723192 -0.90151407 -0.4214714 -0.01342527</code></pre>
</div>
</div>
<ul>
<li>Los valores propios son:</li>
</ul>
<p><span class="math display">\[\lambda_1=136.615,\quad \lambda_2=8.861,\quad \lambda_3 = 0.738,\quad \lambda_4 = 0.047.\]</span></p>
<ul>
<li>Los vectores propios ortonormales correspondientes a los valores propios, son los que aparecen con el nombre: <code>$vectors</code></li>
</ul>
<p>Las expresiones de las variables nuevas <span class="math inline">\(CP_i\)</span> en función de las antiguas, notemos que se calculan sobre los datos centrados, son:</p>
<p><span class="math display">\[\begin{array}{rl}
CP_1 = &amp; 0.934\cdot \tilde{X}_1 + 0.339\cdot \tilde{X}_2 + 0.047\cdot
\tilde{X}_3\\ &amp; + 0.097 \cdot \tilde{X}_4, \\
CP_2 = &amp; -0.022\cdot \tilde{X}_1 +0.354\cdot \tilde{X}_2 -0.248 \cdot
\tilde{X}_3 \\ &amp; -0.902 \cdot \tilde{X}_4, \\
CP_3 = &amp; 0.256\cdot \tilde{X}_1 -0.661 \cdot \tilde{X}_2 +0.566\cdot \tilde{X}_3\\ &amp;-0.421\cdot \tilde{X}_4, \\
CP_4 = &amp; 0.247 \cdot \tilde{X}_1 - 0.568\cdot \tilde{X}_2 - 0.785\cdot
\tilde{X}_3 \\ &amp; - 0.013 \cdot \tilde{X}_4.
\end{array}\]</span></p>
<p>La nueva matriz de datos respecto de las nuevas variables será:</p>
<p><br><br></p>
<p><span class="math display">\[\mathbf{CP}= \tilde{\mathbf{X}} \mathbf{u} =
\left(
\begin{array}{rrrr}
-3.054 &amp; 0.201 &amp; -0.827 &amp; 0.280 \\
-12.719 &amp; 2.480 &amp; -0.333 &amp; 0.103 \\
-4.293 &amp; -3.295 &amp; -0.025 &amp; -0.228 \\
7.373 &amp; -6.736 &amp; -0.183 &amp; 0.029 \\
-15.299 &amp; 0.565 &amp; 1.029 &amp; 0.183 \\
-1.354 &amp; 1.319 &amp; 1.463 &amp; -0.321 \\
-6.997 &amp; 1.411 &amp; -1.460 &amp; -0.233 \\
13.677 &amp; 0.437 &amp; 0.629 &amp; 0.282 \\
22.666 &amp; 3.618 &amp; -0.292 &amp; -0.095 \\
\end{array}
\right)\]</span></p>
<p>Podéis revisar que si se multiplican escalarmente dos columnas cualesquiera, el resultado es nulo. Es decir, las columnas de la nueva matriz de datos son ortogonales dos a dos.</p>
<p>Si representamos gráficamente las dos primeras componentes, podemos observar que se puede distinguir entre niños y niñas con las dos primeras componentes.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="ACP_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/pairs_2.PNG" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./Inferencia.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Inferencia multivariante en poblaciones normales</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./references.html" class="pagination-link">
        <span class="nav-page-text">References</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Análisis de Datos UIB</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Este libro se ha creado con <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>