<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.433">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Análisis de datos - 2&nbsp; Análisis Multivariante</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./Inferencia.html" rel="next">
<link href="./intro.html" rel="prev">
<link href="./atlas.jpeg" rel="icon" type="image/jpeg">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./EM.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Análisis Multivariante</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Análisis de datos</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/AprendeR-UIB/AD/Enlaces" rel="" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Alternar modo lector">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentación</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción al Análisis de Datos</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./EM.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Análisis Multivariante</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Inferencia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Inferencia multivariante en poblaciones normales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ACP.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Análisis de Componentes Principales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./MDS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Escalamiento multidimensional (MDS)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Clustering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Agrupamiento (Clustering)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Series_temporales.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Series temporales</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#poblaciones-vectores-aleatorios" id="toc-poblaciones-vectores-aleatorios" class="nav-link active" data-scroll-target="#poblaciones-vectores-aleatorios"><span class="header-section-number">2.1</span> Poblaciones: vectores aleatorios</a></li>
  <li><a href="#covarianza" id="toc-covarianza" class="nav-link" data-scroll-target="#covarianza"><span class="header-section-number">2.2</span> Covarianza</a></li>
  <li><a href="#correlación" id="toc-correlación" class="nav-link" data-scroll-target="#correlación"><span class="header-section-number">2.3</span> Correlación</a></li>
  <li><a href="#estadística-descriptiva-muestras" id="toc-estadística-descriptiva-muestras" class="nav-link" data-scroll-target="#estadística-descriptiva-muestras"><span class="header-section-number">2.4</span> Estadística descriptiva: Muestras</a>
  <ul class="collapse">
  <li><a href="#covarianza-1" id="toc-covarianza-1" class="nav-link" data-scroll-target="#covarianza-1"><span class="header-section-number">2.4.1</span> Covarianza</a></li>
  <li><a href="#correlación-de-pearson" id="toc-correlación-de-pearson" class="nav-link" data-scroll-target="#correlación-de-pearson"><span class="header-section-number">2.4.2</span> Correlación de Pearson</a></li>
  <li><a href="#estimación" id="toc-estimación" class="nav-link" data-scroll-target="#estimación"><span class="header-section-number">2.4.3</span> Estimación</a></li>
  <li><a href="#correlación-de-spearman" id="toc-correlación-de-spearman" class="nav-link" data-scroll-target="#correlación-de-spearman"><span class="header-section-number">2.4.4</span> Correlación de Spearman</a></li>
  </ul></li>
  <li><a href="#contrastes-de-correlación" id="toc-contrastes-de-correlación" class="nav-link" data-scroll-target="#contrastes-de-correlación"><span class="header-section-number">2.5</span> Contrastes de correlación</a></li>
  <li><a href="#gráficos-para-datos-multidimensionales" id="toc-gráficos-para-datos-multidimensionales" class="nav-link" data-scroll-target="#gráficos-para-datos-multidimensionales"><span class="header-section-number">2.6</span> Gráficos para datos multidimensionales</a>
  <ul class="collapse">
  <li><a href="#otro-gráfico-para-datos-bivariantes" id="toc-otro-gráfico-para-datos-bivariantes" class="nav-link" data-scroll-target="#otro-gráfico-para-datos-bivariantes"><span class="header-section-number">2.6.1</span> Otro gráfico para datos bivariantes</a></li>
  <li><a href="#matriz-de-dispersión" id="toc-matriz-de-dispersión" class="nav-link" data-scroll-target="#matriz-de-dispersión"><span class="header-section-number">2.6.2</span> Matriz de dispersión</a></li>
  <li><a href="#caras-de-chernoff" id="toc-caras-de-chernoff" class="nav-link" data-scroll-target="#caras-de-chernoff"><span class="header-section-number">2.6.3</span> Caras de Chernoff</a></li>
  <li><a href="#matriz-de-correlaciones" id="toc-matriz-de-correlaciones" class="nav-link" data-scroll-target="#matriz-de-correlaciones"><span class="header-section-number">2.6.4</span> Matriz de correlaciones</a></li>
  <li><a href="#gráficos-de-mosaico" id="toc-gráficos-de-mosaico" class="nav-link" data-scroll-target="#gráficos-de-mosaico"><span class="header-section-number">2.6.5</span> Gráficos de mosaico</a></li>
  </ul></li>
  <li><a href="#práctica-3" id="toc-práctica-3" class="nav-link" data-scroll-target="#práctica-3"><span class="header-section-number">2.7</span> <span style="color: red;"><em>Práctica 3</em></span></a></li>
  <li><a href="#distancias" id="toc-distancias" class="nav-link" data-scroll-target="#distancias"><span class="header-section-number">2.8</span> Distancias</a>
  <ul class="collapse">
  <li><a href="#distancia-euclídea" id="toc-distancia-euclídea" class="nav-link" data-scroll-target="#distancia-euclídea"><span class="header-section-number">2.8.1</span> Distancia euclídea</a></li>
  <li><a href="#distancia-de-minkowski" id="toc-distancia-de-minkowski" class="nav-link" data-scroll-target="#distancia-de-minkowski"><span class="header-section-number">2.8.2</span> Distancia de Minkowski</a></li>
  </ul></li>
  <li><a href="#distancias-basadas-en-la-correlación" id="toc-distancias-basadas-en-la-correlación" class="nav-link" data-scroll-target="#distancias-basadas-en-la-correlación"><span class="header-section-number">2.9</span> Distancias basadas en la correlación</a></li>
  <li><a href="#distancia-de-mahalanobis" id="toc-distancia-de-mahalanobis" class="nav-link" data-scroll-target="#distancia-de-mahalanobis"><span class="header-section-number">2.10</span> Distancia de Mahalanobis</a></li>
  <li><a href="#distancias-para-variables-binarias" id="toc-distancias-para-variables-binarias" class="nav-link" data-scroll-target="#distancias-para-variables-binarias"><span class="header-section-number">2.11</span> Distancias para variables binarias:</a></li>
  <li><a href="#distancias-para-variables-categóricas" id="toc-distancias-para-variables-categóricas" class="nav-link" data-scroll-target="#distancias-para-variables-categóricas"><span class="header-section-number">2.12</span> Distancias para variables categóricas:</a></li>
  <li><a href="#distancias-para-variables-mixtas" id="toc-distancias-para-variables-mixtas" class="nav-link" data-scroll-target="#distancias-para-variables-mixtas"><span class="header-section-number">2.13</span> Distancias para variables mixtas</a></li>
  <li><a href="#visualización-de-matrices-de-distancias" id="toc-visualización-de-matrices-de-distancias" class="nav-link" data-scroll-target="#visualización-de-matrices-de-distancias"><span class="header-section-number">2.14</span> Visualización de matrices de distancias</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/AprendeR-UIB/AD/Enlaces/edit/main/EM.qmd" class="toc-action">Editar esta página</a></p><p><a href="https://github.com/AprendeR-UIB/AD/Enlaces/issues/new" class="toc-action">Informar de un problema</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Análisis Multivariante</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>En general, los datos que se recogen en experimentos son multidimensionales: miden diversas variables aleatorias sobre una misma muestra de individuos. Esta información se organiza en tablas de datos con filas que representan a los individuos observados y cada columna corresponde a una variable diferente. Lo que hacemos es evaluar un vector de variables aleatorias (que llamaremos <strong>vector aleatorio</strong>) sobre los individuos de una población.</p>
<p>En esta parte vamos a introducir algunos conceptos sobre vectores de variables aleatorias y tablas multidimensionales de datos cuantitativos.</p>
<section id="poblaciones-vectores-aleatorios" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="poblaciones-vectores-aleatorios"><span class="header-section-number">2.1</span> Poblaciones: vectores aleatorios</h2>
<p>Un <strong>vector aleatorio de dimensión <span class="math inline">\(p\)</span></strong> es un vector formado por <span class="math inline">\(p\)</span> variables aleatorias <span class="math display">\[
\underline{X}=(X_1,X_2,\ldots,X_p).
\]</span> Una <strong>realización</strong> de <span class="math inline">\(\underline{X}\)</span> es un vector <span class="math inline">\((x_1,\ldots,x_p)\)</span> formado por los valores <span class="math inline">\(X_1,\ldots,X_p\)</span> sobre un individuo.</p>
<p>Una <strong>muestra</strong> de <span class="math inline">\(\underline{X}\)</span> es un conjunto de realizaciones.</p>
<p>Usualmente, organizamos una muestra de <span class="math inline">\(\underline{X}\)</span> por medio de una tabla de datos con las columnas definidas por las variables <span class="math inline">\(X_1,\ldots,X_p\)</span> y donde cada fila es una realización de estas variables, es decir, un vector formado por los valores de <span class="math inline">\(X_1,\ldots,X_p\)</span> sobre un individuo de la muestra.</p>
<p><span style="color: blue;"><em>Ejemplo</em></span>: Sea <span class="math inline">\(\textit{BMI}\)</span> la variable aleatoria que registra el índice de masa corporal (BMI) de una persona, <span class="math inline">\(C\)</span> la variable aleatoria que registra el nivel de colesterol en mg/dl de una persona y <span class="math inline">\(E\)</span> la variable aleatoria que da la edad de una persona en años, entonces <span class="math display">\[
\underline{X}=(\textit{BMI},C,E)
\]</span> es un <strong>vector aleatorio</strong> de dimensión 3. Cada vez que tomamos una persona y anotamos el BMI, el nivel de colesterol y la edad y organizamos estas medidas en este orden en un vector, obtenemos una <strong>realitzación</strong> de este vector aleatorio <span class="math inline">\(\underline{X}\)</span>. Entonces,una <strong>muestra</strong> de <span class="math inline">\(\underline{X}\)</span> será un conjunto de vectores con el BMI, el nivel de colesterol y la edad de un grupo de personas de la población. Por ejemplo</p>
<div class="cell">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">BMI</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">C</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">E</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">18.3</td>
<td style="text-align: right;">170</td>
<td style="text-align: right;">49</td>
</tr>
<tr class="even">
<td style="text-align: right;">24.4</td>
<td style="text-align: right;">202</td>
<td style="text-align: right;">39</td>
</tr>
<tr class="odd">
<td style="text-align: right;">24.6</td>
<td style="text-align: right;">215</td>
<td style="text-align: right;">50</td>
</tr>
<tr class="even">
<td style="text-align: right;">24.4</td>
<td style="text-align: right;">218</td>
<td style="text-align: right;">44</td>
</tr>
<tr class="odd">
<td style="text-align: right;">22.2</td>
<td style="text-align: right;">210</td>
<td style="text-align: right;">40</td>
</tr>
<tr class="even">
<td style="text-align: right;">19.5</td>
<td style="text-align: right;">210</td>
<td style="text-align: right;">36</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>Sean <span class="math inline">\(\underline{X}=(X_1,X_2,\ldots,X_p)\)</span> un vector aleatorio y, <span class="math inline">\(\mu_i\)</span> y <span class="math inline">\(\sigma_i\)</span> la media y la desviación típica, respectivamente, de cada <span class="math inline">\(X_i\)</span>.</p>
<ul>
<li><p>El <strong>valor esperado</strong>, o <strong>vector de medias</strong>, de <span class="math inline">\(\underline{X}\)</span> es el vector formado por los valores esperados, o medias de sus componentes: <span class="math display">\[
E(\underline{X})=(\mu_1,\ldots,\mu_p).
\]</span> Para abreviar, a veces indicaremos este vector simplemente con <span class="math inline">\(\boldsymbol\mu\)</span>.</p></li>
<li><p>El <strong>vector de varianzas</strong> de <span class="math inline">\(\underline{X}\)</span> es el vector formado por las varianzas de sus componentes: <span class="math display">\[
\sigma^2(\underline{X})=(\sigma_1^2,\ldots,\sigma_p^2).
\]</span></p></li>
<li><p>El <strong>vector de desviaciones típicas</strong> de <span class="math inline">\(\underline{X}\)</span> es el vector formado por las desviaciones típicas de sus componentes: <span class="math display">\[
\sigma(\underline{X})=(\sigma_1,\ldots,\sigma_p).
\]</span></p></li>
</ul>
</section>
<section id="covarianza" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="covarianza"><span class="header-section-number">2.2</span> Covarianza</h2>
<p>La <strong>covarianza</strong> de dos variables <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> es una medida del comportamiento conjunto de estas dos variables.</p>
<p>Formalmente, dadas dos variables aleatorias <span class="math inline">\(X,Y\)</span> con medias <span class="math inline">\(\mu_X\)</span> y <span class="math inline">\(\mu_Y\)</span>, respectivamente, su <strong>covarianza</strong> es <span class="math display">\[
\sigma_{X,Y}=E\left((X-\mu_X)\cdot ( Y-\mu_Y)\right).
\]</span> Es fácil comprobar que <span class="math display">\[
\sigma_{X,Y}=E(X\cdot Y) -\mu_X\cdot \mu_Y.
\]</span></p>
<p>En efecto, <span class="math display">\[
\begin{array}{rl}
\sigma_{X,Y} &amp; =E((X-\mu_X) ( Y-\mu_Y))=
E(XY-\mu_XY-\mu_YX+\mu_X\mu_Y)\\ &amp;
=E(XY)-\mu_XE(Y)-\mu_YE(X)+\mu_X\mu_Y\\ &amp;=
E(XY)-\mu_X\mu_Y-\mu_Y\mu_X+\mu_X\mu_Y
=E(XY)-\mu_X\mu_Y
\end{array}
\]</span></p>
<p>La covarianza de <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> puede tomar cualquier valor real (no como la varianza, que siempre es positiva), y mide el grado de variación conjunta de las variables en el sentido sigüiente:</p>
<ul>
<li><span class="math inline">\(\sigma_{X,Y}&gt;0\)</span> significa que cuando <span class="math inline">\(X\)</span> es más grande en un individuo 1 que en un individuo 2, <span class="math inline">\(Y\)</span> tiende también a ser más gran en el individuo 1 que en el individuo 2.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><span class="math inline">\(\sigma_{X,Y}&lt;0\)</span> significa que cuando <span class="math inline">\(X\)</span> es más grande en un individuo 1 que en un individuo 2, <span class="math inline">\(Y\)</span> tiende a ser más pequeña en el individuo 1 que en el individuo 2.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<ul>
<li><span class="math inline">\(\sigma_{X,Y}=0\)</span> significa que no hay ninguna tendencia en este sentido.</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>El signo de la covarianza refleja la “tendencia del crecimiento conjunto” de las variables:</p>
<ul>
<li><p>Covarianza positiva significa la misma tendencia: Si <span class="math inline">\(X\)</span> aumenta, <span class="math inline">\(Y\)</span> tiende a aumentar. Esto suele expresarse diciendo que hay <strong>asociación positiva</strong> entre <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span>.</p></li>
<li><p>Covarianza negativa significa la tendencia inversa: Si <span class="math inline">\(X\)</span> aumenta, <span class="math inline">\(Y\)</span> tiende a disminuir. Esto suele expresarse diciendo que hay <strong>asociación negativa</strong> entre <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span>.</p></li>
</ul>
<p><strong>Si <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> son variables independientes, su covarianza es 0</strong>, porque en este caso <span class="math inline">\(E(X\cdot Y) =\mu_X\mu_Y\)</span> y por tanto <span class="math display">\[
\sigma_{X,Y}=E(X\cdot Y) -\mu_X\cdot \mu_Y=\mu_X\cdot \mu_Y-\mu_X\cdot \mu_Y=0.
\]</span> Intuitivamente, si <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> son independientes, significa que el hecho de que el valor de <span class="math inline">\(X\)</span> aumente de un individuo a otro no tiene ningún efecto sobre el valor de <span class="math inline">\(Y\)</span>.</p>
<p>¿Por qué, si <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> son independientes, <span class="math inline">\(E(X\cdot Y) =\mu_X\mu_Y\)</span>?</p>
<p>Os lo demostraremos en el caso discreto; el argumento en el caso continuo es lo mismo cambiando sumatorios por integrales. <span class="math display">\[
\begin{array}{rl}
E(X\cdot Y)\!\!\! &amp;\displaystyle =\sum_{x\in D_X,y\in D_Y} xyP(X=x,Y=y)\\
&amp;\displaystyle =\sum_{x\in D_X,y\in D_Y} xyP(X=x)P(Y=y)\\
&amp;\text{(por la independencia de $X$ e $Y$)}\\
&amp;\displaystyle =\Big(\sum_{x\in D_X}xP(X=x)\Big)\Big(\sum_{y\in D_Y} yP(Y=y)\Big)=E(X)E(Y)
\end{array}
\]</span></p>
<p>Es importante remarcar que la igualdad <span class="math inline">\(E(X\cdot Y) =\mu_X\mu_Y\)</span> es equivalente a la igualdad <span class="math inline">\(\sigma(X+Y)^2 =\sigma(X)^2+\sigma(Y)^2\)</span> que decíamos que satisfacen las variables independientes. En efecto <span class="math display">\[
\begin{array}{l}
\sigma(X+Y)^2 -(\sigma(X)^2+\sigma(Y)^2)\\
\quad = E((X+Y)^2)-E(X+Y)^2-(E(X^2)-E(X)^2+E(Y^2)-E(Y)^2)\\
\quad = E(X^2+2XY+Y^2)-(E(X)+E(Y))^2\\
\qquad\qquad -E(X^2)+E(X)^2-E(Y^2)+E(Y)^2\\
\quad = E(X^2)+2E(XY)+E(Y^2)-E(X)^2-2E(X)E(Y)-E(Y)^2\\
\qquad\qquad -E(X^2)+E(X)^2-E(Y^2)+E(Y)^2\\
\quad = 2E(XY)-2E(X)E(Y)=2(E(XY)-\mu_X\mu_Y)
\end{array}
\]</span> y por tanto <span class="math display">\[
\sigma^2(X+Y) -(\sigma^2(X)+\sigma^2(Y))=0 \Longleftrightarrow E(XY)-\mu_X\mu_Y=0
\]</span></p>
<p><strong>Si <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> son variables independendientes, su covarianza es 0</strong>, pero la implicación al contrario es falsa: <strong>Dos variables aleatorias pueden tener covarianza 0 y no ser independientes</strong>.</p>
<p>Veamos un ejemplo de este hecho:</p>
<p>Supongamos que tenemos un dado tetraédrico no trucado con las caras marcadas con los valores -2, -1, 1 y 2. Sean <span class="math inline">\(X\)</span> la variable aleatoria que consiste en llanzar el dado y anotar el resultado (la cara que queda en tierra), e <span class="math inline">\(Y\)</span> la variable aleatoria que consite en lanzar el dado y anotar el <em>cuadrado</em> del resultado obtenido. Como las cuatro caras del dado son equiprobables, <span class="math display">\[
\begin{array}{l}
\displaystyle P(X=-2)=P(X=-1)=P(X=1)=P(X=2)=\frac{1}{4}\\
\displaystyle P(Y=1)=P(Y=4)=\frac{1}{2}
\end{array}
\]</span></p>
<p>Comp <span class="math inline">\(Y\)</span> es función de <span class="math inline">\(X\)</span>, ya que <span class="math inline">\(Y=X^2\)</span>, <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> no pueden ser independientes. Veamos que, en efecto, no lo son. Observad que los únicos posibles valores para el vector <span class="math inline">\((X,Y)\)</span> en una tirada del dado son (-2,4), (-1,1), (1,1) y (2,4), cada uno con probabilidad 1/4. Entonces, por ejemplo, la probabilidad de obtener en una tirada <span class="math inline">\(X=-1\)</span> i <span class="math inline">\(Y=4\)</span> es 0, porque es imposible, mientras que <span class="math display">\[
P(X=-1)\cdot P(Y=4)=\frac{1}{4}\cdot\frac{1}{2}=\frac{1}{8}\neq 0.
\]</span></p>
<p>Veamos ahora que la covarianza de <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> es 0. Para calcularla, primero necesitamos calcular los valores esperados de las variables: <span class="math display">\[
\begin{array}{l}
\displaystyle \mu_X=(-2)\cdot \frac{1}{4}+(-1)\cdot \frac{1}{4}+1\cdot \frac{1}{4}+2\cdot \frac{1}{4}=0\\
\displaystyle \mu_Y=1\cdot \frac{1}{2}+4\cdot \frac{1}{2}=2.5
\end{array}
\]</span> Por tanto <span class="math display">\[
\begin{array}{l}
\sigma_{X,Y}=E\big(X\cdot Y\big)-\mu_X\cdot \mu_Y=E\big(X\cdot Y\big)-0\cdot 2.5=E\big(X\cdot Y\big)\\
\qquad =P\big(X=-2,Y=4\big)\cdot (-2\cdot 4)+P\big(X=-1,Y=1\big)\cdot (-1\cdot 1)\\
\qquad\qquad\qquad +P\big(X=1,Y=1\big)\cdot (1\cdot 1)+P\big(X=2,Y=4\big)\cdot (2\cdot 4)\\
\qquad =\displaystyle \frac{1}{4}\cdot (-8)+\frac{1}{4}\cdot (-1)+\frac{1}{4}\cdot 1+\frac{1}{4}\cdot 8=0.
\end{array}
\]</span> Así pues, <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> son variables dependientes, pero su covarianza es 0.</p>
<p>Dos propiedades importantes más de la covarianza:</p>
<ul>
<li><p>La covarianza es simétrica: <span class="math display">\[
\begin{array}{rl}
\sigma_{X,Y}\!\!\! &amp; =E((X-\mu_X)\cdot ( Y-\mu_Y))\\
&amp; =E(( Y-\mu_Y)\cdot (X-\mu_X))=\sigma_{Y,X}
\end{array}
\]</span></p></li>
<li><p>La covarianza de una variable aleatoria con ella misma es su varianza: <span class="math display">\[
\sigma_{X,X}=E((X-\mu_X)^2)=\sigma^2(X)
\]</span></p></li>
</ul>
<p>La <strong>matriz de covarianzas</strong> de un vector aleatorio <span class="math inline">\(\underline{X}=(X_1,\ldots,X_p)\)</span> es la matriz formada por las covarianzas de los pares de variables que la formen: <span class="math display">\[
\sigma_{\underline{X},\underline{X}}=\begin{pmatrix} \sigma_{X_1,X_1} &amp; \sigma_{X_1,X_2} &amp; \ldots &amp; \sigma_{X_1,X_p}\\
\sigma_{X_2,X_1} &amp; \sigma_{X_2,X_2} &amp; \ldots &amp; \sigma_{X_2,X_p}\\
\vdots &amp; \vdots &amp;\ddots  &amp; \vdots\\
\sigma_{X_p,X_1} &amp; \sigma_{X_p,X_2} &amp; \ldots &amp; \sigma_{X_p,X_p}\\
\end{pmatrix}
\]</span></p>
<p>Esta matriz es simétrica y las entradas de la diagonal son las varianzas de las variables del vector, porque <span class="math inline">\(\sigma_{X_i,X_i}=\sigma^2_{X_i}\)</span>.</p>
</section>
<section id="correlación" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="correlación"><span class="header-section-number">2.3</span> Correlación</h2>
<p>Como hemos dicho, el signo de la covarianza tiene una interpretación sencilla, puesto que refleja la tendencia del crecimiento conjunto de las variables. Pero, su magnitud no tiene una interpretación sencilla.</p>
<p>Como alternativa, se puede medir la tendencia de que haya una <em>relación lineal</em> entre dos variables aleatorias <strong>continuas</strong> empleando el llamado <em>coeficiente de correlación lineal de Pearson</em> (o, para abreviar, la <strong>correlación</strong>), que viene a ser una versión normalizada de la covarianza.</p>
<p>En concreto, la <strong>correlación</strong> de las variables <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> se define como el cociente de su covarianza entre el producto de sus desviaciones típicas: <span class="math display">\[
\rho_{X,Y}=\frac{\sigma_{X,Y}}{\sigma_{X} \sigma_{Y}}
\]</span></p>
<p>La correlación tiene las propiedades importantes siguientes:</p>
<ol type="1">
<li><p>No tiene unidades (porque las unidades de <span class="math inline">\(\sigma_X\)</span> son las de <span class="math inline">\(X\)</span>, las unidades de <span class="math inline">\(\sigma_Y\)</span> son las de <span class="math inline">\(Y\)</span>, y las unidades de <span class="math inline">\(\sigma_{X,Y}\)</span> son las de <span class="math inline">\(X\)</span> por las de <span class="math inline">\(Y\)</span>)</p></li>
<li><p>Toma valores entre -1 y 1: <span class="math inline">\(-1\leqslant \rho_{X,Y}\leqslant 1\)</span></p></li>
<li><p>Es simétrica, <span class="math inline">\(\rho_{X,Y}= \rho_{Y,X}\)</span></p></li>
<li><p>La correlación de una variable con ella misma es 1: <span class="math inline">\(\rho_{X,X}=1\)</span></p></li>
<li><p><span class="math inline">\(\rho_{X,Y}=\pm 1\)</span> si, y solo si, las variables <span class="math inline">\(X,Y\)</span> tienen una <em>relación lineal perfecta</em>. Es decir, <span class="math inline">\(\rho_{X,Y}=\pm 1\)</span> si, y solo si, existen <span class="math inline">\(a,b\in \mathbb{R}\)</span> con <span class="math inline">\(a\neq 0\)</span> y tales que <span class="math inline">\(Y= X+b\)</span>. La pendiente <span class="math inline">\(a\)</span> de esta recta tiene el mismo signo que <span class="math inline">\(\rho_{X,Y}\)</span>.</p></li>
<li><p>Cuanto más se acerca <span class="math inline">\(|\rho_{X,Y}|\)</span> a 1, más se acerca <span class="math inline">\(Y\)</span> a ser función lineal de <span class="math inline">\(X\)</span>.</p></li>
</ol>
<ul>
<li>Si <span class="math inline">\(\rho_{X,Y}&gt;0\)</span>, la función es creciente</li>
<li>Si <span class="math inline">\(\rho_{X,Y}&lt;0\)</span>, la función es decreciente</li>
</ul>
<ol start="6" type="1">
<li>Si <span class="math inline">\(\rho_{X,Y}=0\)</span>, decimos que las variables <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> son <strong>incorreladas</strong>. Notamos que la correlación es 0 si, y solo si, la covarianza es 0. Por lo tanto, <em>si <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span> son independientes, también son incorreladas. El recíproco en general es falso</em>.</li>
</ol>
<p>Si una de las dos variables tiene desviación típica 0, en la fórmula de la correlación aparece un 0 en el denominador y no la podemos calcular. En este caso, se toma <span class="math inline">\(\rho_{X,Y}=0\)</span>. El motivo intuitivo es que una variable constante es siempre independiente de cualquier otra variable (haga lo que haga la otra, siempre toma el mismo valor) y hemos quedado que las variables independientes son incorreladas.</p>
<p>La <em>matriz de correlaciones</em> de un vector aleatorio <span class="math inline">\(\underline{X}=(X_1,\ldots,X_p)\)</span> es la matriz formada por las correlaciones de pares de sus variables: <span class="math display">\[
\rho(\underline{X})
=\begin{pmatrix} 1 &amp; \rho_{X_1,X_2} &amp; \ldots &amp; \rho_{X_1,X_p}\\
\rho_{X_2,X_1} &amp; 1 &amp; \ldots &amp; \rho_{X_2,X_p}\\
\vdots &amp; \vdots &amp; \ddots &amp; \vdots\\
\rho_{X_p,X_1} &amp; \rho_{X_p,X_2} &amp; \ldots &amp; 1\\
\end{pmatrix}.
\]</span> Esta matriz es simétrica por la simetría de la correlación.</p>
<p>La correlación de Pearson de dos variables continuas mide la tendencia de las variables a variar conjuntamente de manera lineal. En particular, por ejemplo, si <span class="math inline">\(\rho_{X,Y}&gt;0\)</span>, <span class="math inline">\(Y\)</span> tiende a crecer cuando <span class="math inline">\(X\)</span> crece. Pero esto no significa que un aumento del valor de <span class="math inline">\(X\)</span> cause que el valor de <span class="math inline">\(Y\)</span> tienda a aumentar:</p>
<blockquote class="blockquote">
<p><strong>Correlación no implica causalidad!</strong></p>
</blockquote>
<p>La tendencia al crecimiento simultáneo de <span class="math inline">\(X\)</span> y <span class="math inline">\(Y\)</span> se puede deber a una tercera variable que las haga crecer las dos, o puede ser puramente espuria.</p>
<p>Si entráis a la página web <a href="https://tylervigen.com/spurious-correlations"><em>Spurious Correlations</em></a> podréis explorar un montón de correlaciones espurias. Nuestra preferida es una correlación de 0.947 entre la variable <span class="math inline">\(X\)</span>= “Tomo un año y anoto el consumo per capita* de queso en los EE. UU.” e <span class="math inline">\(Y\)</span>= “Tomo un año y anoto el número de muertes por estrangulamiento accidental con las sábanas de la cama en los EE. UU.”.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/spurcorr1.png" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Hay un ejemplo de correlación negativa que es importante tener presente para no dejarse engañar.</p>
<p><strong>Teorema</strong>: Si <span class="math inline">\(X_1\)</span>, <span class="math inline">\(X_2\)</span> son dos copias independientes de una misma variable aleatoria <span class="math inline">\(X\)</span>, <span class="math display">\[
\rho_{X_1,X_2-X_1}=-\frac{1}{\sqrt{2}}\approx -0.71
\]</span></p>
<p>Esto nos dice que, sea cual sea la variable <span class="math inline">\(X\)</span>, si la medimos en dos momentos independientes o sobre dos individuos elegidos de manera independiente, la diferencia entre los dos valores <em>tiene una tendencia destacada a decrecer linealmente</em> en el primer valor. Por ejemplo:</p>
<ul>
<li><p>Hacéis un test y sacáis una nota muy baja (<span class="math inline">\(X_1\)</span>). El día siguiente hacéis otro test similar (<span class="math inline">\(X_2\)</span>) sin haber estudiado más. Lo más probable es que, por puro azar, saques una nota más alta (que <span class="math inline">\(X_2-X_1\)</span> sea grande, por lo tanto positivo).</p></li>
<li><p>Hacéis un test y sacáis una nota muy alta (<span class="math inline">\(X_1\)</span>). El día siguiente hacéis otro test (<span class="math inline">\(X_2\)</span>) sin haber estudiado más. Lo más probable es que, por puro azar, saques una nota más baja (que <span class="math inline">\(X_2-X_1\)</span> sea pequeño, por lo tanto negativo).</p></li>
</ul>
<p>Por si alguno necesita una demostración del teorema anterior, recordamos que <span class="math display">\[
\rho_{X_1,X_2-X_1}=\dfrac{\sigma_{X_1,X_2-X_1}}{\sigma_{X_1}\sigma_{X_2-X_1}}
\]</span> Ahora <span class="math display">\[
\begin{array}{l}
\sigma_{X_2-X_1}=\sqrt{\sigma^2_{X_2-X_1}}\\[2ex]
\quad =\sqrt{\sigma^2_{X_1}+\sigma^2_{X_2}}\ \text{(porque son independientes)}\\[2ex]
\quad =\sqrt{\sigma^2_{X}+\sigma^2_{X}}\ \text{(porque $X_1,X_2$ son copias de $X$)}\\[2ex]
\quad =\sqrt{2\sigma^2_{X}}=\sigma_{X}\sqrt{2}
\end{array}
\]</span> Luego, <span class="math display">\[
\begin{array}{l}
\sigma_{X_1,X_2-X_1}=E(X_1(X_2-X_1))-E(X_1)E(X_2-X_1)\\[1ex]
\quad =E(X_1X_2-X_1^2)-E(X_1)(E(X_2-E(X_1))\\[1ex]
\quad =E(X_1X_2)-E(X_1^2)-E(X_1)E(X_2)+E(X_1)E(X_1)\\[1ex]
\quad =E(X_1)E(X_2)-E(X_1^2)-E(X_1)E(X_2)+E(X_1)E(X_1)\\[1ex]
\quad \text{(porque  $X_1,X_2$ son independents)}\\[1ex]
\quad =-E(X_1^2)+E(X_1)E(X_1)=-\sigma^2_{X_1}=-\sigma^2_{X}
\end{array}
\]</span></p>
<p>Combinando lo anterior: <span class="math display">\[
\rho_{X_1,X_2-X_1}=\dfrac{\sigma_{X_1,X_2-X_1}}{\sigma_{X_1}\sigma_{X_2-X_1}}=\dfrac{-\sigma^2_{X}}{\sigma_{X}\cdot \sigma_{X}\sqrt{2}} =-\frac{1}{\sqrt{2}}
\]</span></p>
<p>Como ejemplo, generaremos una muestra <span class="math inline">\(X\)</span> de 101 “notas” aleatorias entre 0 y 100 con distribución binomial <span class="math inline">\(B(100,0.5)\)</span>. Tomaremos como <span class="math inline">\(X_1\)</span> el vector de las primeras 100 notas, <span class="math display">\[
X_1=(x_1,x_2,\ldots,x_{100})
\]</span> y como <span class="math inline">\(X_2-X_1\)</span> el vector de las diferencias de cada nota <span class="math inline">\(x_y\)</span>, <span class="math inline">\(y\geqslant 2\)</span>, con la anterior: <span class="math display">\[
X_2-X_1=(x_2-x_1,x_3-x_2,\ldots,x_{101}-x_{100}).
\]</span> Calcularemos la correlación entre <span class="math inline">\(X_1\)</span> y <span class="math inline">\(X_2-X_1\)</span>, y lo ilustraremos con un gráfico.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>X<span class="ot">=</span><span class="fu">rbinom</span>(<span class="dv">101</span>,<span class="dv">100</span>,<span class="fl">0.5</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>X1<span class="ot">=</span>X[<span class="sc">-</span><span class="dv">101</span>]</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>X2.menos.X1<span class="ot">=</span><span class="fu">diff</span>(X)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(X1,X2.menos.X1,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">xlab=</span><span class="fu">expression</span>(X[<span class="dv">1</span>]),</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab=</span><span class="fu">expression</span>(X[<span class="dv">2</span>]<span class="sc">-</span>X[<span class="dv">1</span>]))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(X1,X2.menos.X1)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.7068097</code></pre>
</div>
</div>
<p>La correlación predicha por el teorema anterior es</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="dv">1</span><span class="sc">/</span><span class="fu">sqrt</span>(<span class="dv">2</span>) </span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.7071068</code></pre>
</div>
</div>
</section>
<section id="estadística-descriptiva-muestras" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="estadística-descriptiva-muestras"><span class="header-section-number">2.4</span> Estadística descriptiva: Muestras</h2>
<section id="covarianza-1" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="covarianza-1"><span class="header-section-number">2.4.1</span> Covarianza</h3>
<p>Sean <span class="math inline">\(X=(x_1,\ldots,x_n)\)</span> y <span class="math inline">\(Y=(y_1,\ldots,y_n)\)</span> dos vectores obtenidos de mediciones de dos variables aleatorias cuantitativas sobre una misma muestra ordenada de individuos de tamño <span class="math inline">\(n\)</span> de una población. Sean <span class="math inline">\(\overline{X}\)</span> y <span class="math inline">\(\overline{Y}\)</span> sus medias muestrales. Entonces su <em>covarianza muestral</em> es <span class="math display">\[
\widetilde{S}_{X,Y} =\frac{1}{n-1} \sum_{i =1}^n\big((x_{i}-\overline{{X}})(y_i-\overline{Y})\big)
\]</span> y su <strong>covarianza</strong> (<strong>a secas</strong>) es <span class="math display">\[
{S}_{X,Y} =\frac{1}{n} \sum_{i =1}^n\big((x_{i}-\overline{{X}})(y_i-\overline{Y})\big)=\frac{n-1}{n}\widetilde{S}_{X,Y}.
\]</span> Es decir, la diferencia entre la versión “muestral” y la versión “a secas” recae en el denominador, <span class="math inline">\(n-1\)</span> y <span class="math inline">\(n\)</span> respectivamente.</p>
<blockquote class="blockquote">
<p>La covarianza de dos vectores solo tiene sentido cuando estos vectores representan los valores de dos variables cuantitativas sobre los mismos individuos, o sobre dos muestras emparejadas, y en el mismo orden. En particular, los dos vectores tienen que tener la misma longitud.</p>
</blockquote>
<p>Como en el caso poblacional, la <strong>covarianza</strong> entre dos vectores mide la tendencia que tienen los datos a variar conjuntamente:</p>
<ul>
<li><p>Cuando <span class="math inline">\(\widetilde{S}_{X,Y}&gt;0\)</span>, si <span class="math inline">\(x_i&gt;x_j\)</span> entonces <span class="math inline">\(y_i\)</span> tiende a ser más grande que <span class="math inline">\(y_j\)</span></p></li>
<li><p>Cuando <span class="math inline">\(\widetilde{S}_{X,Y}&lt;0\)</span>, si <span class="math inline">\(x_i&gt;x_j\)</span> entonces <span class="math inline">\(y_i\)</span> tiende a ser más pequeño que <span class="math inline">\(y_j\)</span></p></li>
<li><p>Cuando <span class="math inline">\(\widetilde{S}=0\)</span>, no hay ninguna tendencia en este sentido</p></li>
</ul>
<p>Es fácil comprobar que:</p>
<ul>
<li>Las dos covarianzas son simétricas <span class="math display">\[
\widetilde{S}_{X,Y}=\widetilde{S}_{Y,X},\ {S}_{X,Y}={S}_{Y,X}
\]</span></li>
<li>La varianza de un vector es su covarianza con él mismo <span class="math display">\[
\widetilde{S}_{X,X}=\widetilde{S}^2_{X},\ {S}_{X,X}={S}^2_{X}.
\]</span></li>
</ul>
<p><span style="color: blue;"><em>Ejemplo</em></span></p>
<p>Hemos medido el índice de masa corporal, BMI, y el nivel de colesterol en 5 individuos sanos. Guardamos los resultados en un <em>dataframe</em> y calculamos las medias:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>BMI<span class="ot">=</span> <span class="fu">c</span>(<span class="fl">18.3</span>,<span class="fl">24.4</span>,<span class="fl">24.6</span>,<span class="fl">24.4</span>,<span class="fl">22.2</span>,<span class="fl">19.5</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>Chol<span class="ot">=</span><span class="fu">c</span>(<span class="dv">170</span>,<span class="dv">202</span>,<span class="dv">215</span>,<span class="dv">218</span>,<span class="dv">210</span>,<span class="dv">210</span>)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>DF<span class="ot">=</span><span class="fu">data.frame</span>(BMI,Chol)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(BMI)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 22.23333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(Chol)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 204.1667</code></pre>
</div>
</div>
<p>Entonces la covarianza muestral de estos dos vectores es <span class="math display">\[
\begin{array}{l}
\dfrac{1}{5}\Big((18.3-22.23)(170-204.17)+(24.4-22.23)(202-204.17)\\
\qquad +(24.6-22.23)(215-204.17)+(24.4-22.23)(218-204.17)\\
\qquad +(22.2-22.23)(210-204.17)+(19.5-22.23)(210-204.17)\Big)=33.8333
\end{array}
\]</span></p>
<p>Entonces la covarianza muestral de estos dos vectores es <span class="math display">\[
\begin{array}{l}
\dfrac{1}{6}\Big((18.3-22.23)(170-204.17)+(24.4-22.23)(202-204.17)\\
\qquad +(24.6-22.23)(215-204.17) +(24.4-22.23)(218-204.17)\\
\qquad +(22.2-22.23)(210-204.17)+(19.5-22.23)(210-204.17)\Big)=28.1944
\end{array}
\]</span></p>
<p>La covarianza <strong>muestral</strong> de dos vectores numéricos de la misma longitud <span class="math inline">\(n\)</span> se calcula en R con la función <code>cov</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(BMI,Chol)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 33.83333</code></pre>
</div>
</div>
<p>Para obtener su covarianza a secas, hay que multiplicar el resultado de <code>cov</code> por <span class="math inline">\((n-1)/n\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>n<span class="ot">=</span><span class="fu">length</span>(BMI)</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(BMI,Chol)<span class="sc">*</span>(n<span class="dv">-1</span>)<span class="sc">/</span>n</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28.19444</code></pre>
</div>
</div>
<p>Consideramos una tabla de datos cuantitativos de la forma <span class="math display">\[
\begin{array}{cccc}
X_1 &amp; X_2 &amp; \ldots &amp; X_p\\ \hline
x_{1 1} &amp; x_{1 2} &amp;\ldots &amp; x_{1 p}\\
x_{2 1} &amp; x_{2 2} &amp;\ldots &amp; x_{2 p}\\
\vdots &amp; \vdots   &amp;   \ddots    &amp;\vdots\\
x_{n 1} &amp; x_{n 2} &amp;\ldots &amp; x_{n p}
\end{array}
\]</span> donde cada columna representa los valores de cierta variable <span class="math inline">\(X_i\)</span> y cada fila un individuo de una muestra de la población, de forma que la entrada <span class="math inline">\(x_{ij}\)</span> de esta tabla es el valor de <span class="math inline">\(X_j\)</span> sobre el individuo <span class="math inline">\(i\)</span>-ésimo de la muestra.</p>
<p>La <em>matriz de covarianzas muestrales</em> de esta tabla es la matriz <span class="math display">\[
\widetilde{{S}}=
\begin{pmatrix}  
\widetilde{S}^2_{X_1} &amp; \widetilde{S}_{X_1,X_2} &amp; \ldots &amp; \widetilde{S}_{X_1,X_p}\\
\widetilde{S}_{X_2,X_1} &amp;  \widetilde{S}^2_{X_2} &amp; \ldots &amp; \widetilde{S}_{X_2,X_p}\\
  \vdots &amp; \vdots  &amp;  \ddots      &amp; \vdots\\
\widetilde{S}_{X_p,X_1} &amp; \widetilde{S}_{X_p,X_2} &amp; \ldots &amp;  \widetilde{S}^2_{X_p}
\end{pmatrix}
\]</span> y la <em>matriz de covarianzas</em> (<em>a secas</em>) se define de manera similar, pero con las covarianzas a secas: <span class="math display">\[
{S}=
\begin{pmatrix}  
S^2_{X_1} &amp; S_{X_1,X_2} &amp; \ldots &amp; S_{X_1,X_p}\\
S_{X_2,X_1} &amp; S^2_{X_2} &amp; \ldots &amp; S_{X_2,X_p}\\
  \vdots &amp; \vdots  &amp;  \ddots      &amp; \vdots\\
S_{X_p,X_1} &amp; S_{X_p,X_2} &amp; \ldots &amp; S^2_{X_p}
\end{pmatrix}
\]</span> Las dos son simétricas.</p>
<p>La matriz de covarianzas muestrales se calcula con la función <code>cov</code> aplicada a la matriz o al data frame de variables numéricas que almacena la tabla de datos. Para calcular la matriz de covarianzas a secas, se multiplica el resultado de <code>cov</code> por <span class="math inline">\((n-1)/n\)</span>, donde <span class="math inline">\(n\)</span> es el número de filas de la tabla.</p>
<p><span style="color: blue;"><em>Ejemplo</em></span></p>
<p>Añadiremos a los datos del ejemplo anterior una tercera variable con las edades de los 5 individuos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>DF<span class="sc">$</span>Edad<span class="ot">=</span><span class="fu">c</span>(<span class="dv">49</span>,<span class="dv">39</span>,<span class="dv">50</span>,<span class="dv">44</span>,<span class="dv">40</span>,<span class="dv">36</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>DF</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   BMI Chol Edad
1 18.3  170   49
2 24.4  202   39
3 24.6  215   50
4 24.4  218   44
5 22.2  210   40
6 19.5  210   36</code></pre>
</div>
</div>
<p>La matriz de covarianzas muestrales de esta tabla es</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(DF)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>           BMI      Chol   Edad
BMI   7.586667  33.83333   1.14
Chol 33.833333 309.76667 -33.00
Edad  1.140000 -33.00000  32.00</code></pre>
</div>
</div>
<p>Podréis observar que es simétrica, que la entrada (2,1) coincide con la covarianza de <code>BMI</code> y <code>Chol</code> que hemos calculado antes, y que en la diagonal obtenemos las varianzas muestrales de las variables de la tabla:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">apply</span>(DF,<span class="at">MARGIN=</span><span class="dv">2</span>,<span class="at">FUN=</span>var)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       BMI       Chol       Edad 
  7.586667 309.766667  32.000000 </code></pre>
</div>
</div>
</section>
<section id="correlación-de-pearson" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2" class="anchored" data-anchor-id="correlación-de-pearson"><span class="header-section-number">2.4.2</span> Correlación de Pearson</h3>
<p>Sean <span class="math inline">\(X=(x_1,\ldots,x_n)\)</span> e <span class="math inline">\(Y=(y_1,\ldots,y_n)\)</span> dos vectores obtenidos midiendo dos variables aleatorias continuas sobre una misma muestra de individuos de medida <span class="math inline">\(n\)</span> de una población.</p>
<p>La <em>correlación de Pearson</em> de <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> es su covarianza muestral dividida por el producto de sus desviaciones típicas muestrales: <span class="math display">\[
R_{X,Y}=\frac{\widetilde{S}_{X,Y}}{\widetilde{S}_X\cdot \widetilde{S}_Y}.
\]</span></p>
<p>La <em>correlación de Pearson</em> de <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> también es igual a su covarianza a secas dividida por el producto de sus desviaciones típicas a secas, porque los cambios de denominador se cancelan: <span class="math display">\[
R_{X,Y}=\frac{\widetilde{S}_{X,Y}}{\widetilde{S}_X\cdot \widetilde{S}_Y}=
\frac{\frac{n}{n-1}\cdot {S}_{X,Y}}{\sqrt{\frac{n}{n-1}}\cdot {S}_X \cdot\sqrt{\frac{n}{n-1}}\cdot{S}_Y}=
\frac{S_{X,Y}}{S_X \cdot S_Y}=R_{X,Y}.
\]</span></p>
<p><span style="color: blue;"><em>Ejemplo</em></span></p>
<p>Volvemos a la situación del ejemplo anterior. La covarianza muestral y las desviaciones típicas muestrales de los vectores <code>BMI</code> y <code>Chol</code> son</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cov</span>(BMI,Chol)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 33.83333</code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(BMI)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.75439</code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(Chol)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17.60019</code></pre>
</div>
</div>
<p>y por tanto su correlación de Pearson es <span class="math display">\[
R_{BMI,Chol}=\frac{33.833}{2.754\cdot 17.6}= 0.698
\]</span></p>
<p>Algunas propiedades importantes de la correlación de Pearson:</p>
<ul>
<li><p>La correlación de Pearson es simétrica: <span class="math display">\[
R_{X,Y}=R_{Y,X}
\]</span></p></li>
<li><p>La correlación de Pearson toma valores solo entre -1 y 1: <span class="math display">\[
-1\leqslant R_{X,Y}\leqslant 1
\]</span></p></li>
<li><p>La correlación de Pearson de un vector con él mismo es 1: <span class="math display">\[
R_{X,X}=1
\]</span></p></li>
<li><p><span class="math inline">\(R_{X,Y}\)</span> tiene el mismo signo que <span class="math inline">\(S_{X,Y}\)</span>, y por tanto este signo tiene el mismo significado que a la covarianza:</p></li>
<li><p>Si <span class="math inline">\(R_{X,Y}&gt;0\)</span> y si <span class="math inline">\(x_i&gt;x_j\)</span>, <span class="math inline">\(y_i\)</span> tiende a ser más grande que <span class="math inline">\(y_j\)</span></p></li>
<li><p>Si <span class="math inline">\(R_{X,Y}&lt;0\)</span> y si <span class="math inline">\(x_i&gt;x_j\)</span>, <span class="math inline">\(y_i\)</span> tiende a ser más pequeño que <span class="math inline">\(y_j\)</span></p></li>
<li><p>Si <span class="math inline">\(R=0\)</span>, no hay ninguna tendencia en este sentido</p></li>
<li><p><span class="math inline">\(R_{X,Y}=\pm 1\)</span> si, y solo si, todos los puntos <span class="math inline">\((x_i,y_i)\)</span> están sobre una recta <span class="math inline">\(y=ax+b\)</span> con <span class="math inline">\(a\neq 0\)</span>. La pendiente <span class="math inline">\(a\)</span> de esta relación lineal tiene el mismo signo que <span class="math inline">\(R_{X,Y}\)</span>. Por lo tanto, la recta es creciente si <span class="math inline">\(R_{X,Y}=1\)</span> y decreciendo si <span class="math inline">\(R_{X,Y}=- 1\)</span>.</p></li>
<li><p>El coeficiente de determinación <span class="math inline">\(R^2\)</span> de la regresión lineal por mínimos cuadrados de <span class="math inline">\(Y\)</span> respecto de <span class="math inline">\(X\)</span> es igual al cuadrado de su correlación de Pearson: <span class="math display">\[
R^2=R_{X,Y}^2
\]</span></p></li>
</ul>
<blockquote class="blockquote">
<p>Por lo tanto, cuanto más se acerca la correlación de Pearson de <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> a 1 o a -1, más se acercan los puntos <span class="math inline">\((x_i,y_i)\)</span> a estar sobre una recta. El signo de <span class="math inline">\(R_{X,Y}\)</span> indica si esta recta es creciente (<span class="math inline">\(R_{X,Y}&gt;0\)</span>) o decreciendo (<span class="math inline">\(R_{X,Y}&lt;0\)</span>).</p>
</blockquote>
<p>Como en el caso poblacional, cuando uno de los vectores es constante, la correlación es igual a 0.</p>
<p>Con R, la correlación de Pearson de dos vectores se puede calcular con la función <code>cor</code>. Por ejemplo, la correlación del Pearson de los vectores <code>BMI</code> y <code>Chol</code> se obtiene con</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(BMI,Chol)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6979141</code></pre>
</div>
</div>
<p>Veamos que su cuadrado es igual al <span class="math inline">\(R^2\)</span> de la regresión lineal de <code>Chol</code> en función de <code>BMI</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(BMI,Chol)<span class="sc">^</span><span class="dv">2</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.487084</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">lm</span>(Chol<span class="sc">~</span>BMI))<span class="sc">$</span>r.squared</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.487084</code></pre>
</div>
</div>
<p>Para hacernos una idea de qué representa este valor de la correlación, veamos el gráfico de los puntos (BMI,Chol) con su recta de regresión lineal:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(BMI,Chol,<span class="at">pch=</span><span class="dv">20</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(Chol<span class="sc">~</span>BMI),<span class="at">col=</span><span class="st">"red"</span>,<span class="at">lwd=</span><span class="fl">1.5</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Podemos observar como <code>Chol</code> tiende a crecer cuando <code>BMI</code> crece, pero los puntos (BMI,Chol) no tienden a estar sobre una recta.</p>
<p><span style="color: red;"><em>Cuidado</em></span> Es conveniente acompañar el cálculo de correlación o covarianza de dos vectores <span class="math inline">\(x,y\)</span> con un gráfico de los puntos <span class="math inline">\((x_i,y_i)\)</span>, porque conjuntos muy diferentes de puntos pueden dar lugar a la misma correlación.</p>
<p>Un ejemplo clásico de este hecho son los cuatro conjuntos de datos <span class="math inline">\((x_{1,i},y_{1,i})_{i=1,\ldots,11}\)</span>, <span class="math inline">\((x_{2,i},y_{2,i})_{i=1,\ldots,11}\)</span>, <span class="math inline">\((x_{3,i},y_{3,i})_{i=1,\ldots,11}\)</span>, <span class="math inline">\((x_{4,i},y_{4,i})_{i=1,\ldots,11}\)</span> que forman el <em>dataframe</em> <code>anscombe</code> de R:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(anscombe)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   11 obs. of  8 variables:
 $ x1: num  10 8 13 9 11 14 6 4 12 7 ...
 $ x2: num  10 8 13 9 11 14 6 4 12 7 ...
 $ x3: num  10 8 13 9 11 14 6 4 12 7 ...
 $ x4: num  8 8 8 8 8 8 8 19 8 8 ...
 $ y1: num  8.04 6.95 7.58 8.81 8.33 ...
 $ y2: num  9.14 8.14 8.74 8.77 9.26 8.1 6.13 3.1 9.13 7.26 ...
 $ y3: num  7.46 6.77 12.74 7.11 7.81 ...
 $ y4: num  6.58 5.76 7.71 8.84 8.47 7.04 5.25 12.5 5.56 7.91 ...</code></pre>
</div>
</div>
<p>Las correlaciones de los cuatro pares de vectores son muy parecidas:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(anscombe<span class="sc">$</span>x1,anscombe<span class="sc">$</span>y1)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8164205</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(anscombe<span class="sc">$</span>x2,anscombe<span class="sc">$</span>y2)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8162365</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(anscombe<span class="sc">$</span>x3,anscombe<span class="sc">$</span>y3)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8162867</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(anscombe<span class="sc">$</span>x4,anscombe<span class="sc">$</span>y4)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8165214</code></pre>
</div>
</div>
<p>Pero si los dibujamos veréis que los cuatro conjuntos de puntos son muy diferentes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(anscombe<span class="sc">$</span>x1,anscombe<span class="sc">$</span>y1,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">main=</span><span class="st">"Conjunto de datos 1"</span>,<span class="at">cex=</span><span class="fl">1.25</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y1<span class="sc">~</span>x1,<span class="at">data=</span>anscombe),<span class="at">col=</span><span class="st">"red"</span>,<span class="at">lwd=</span><span class="fl">1.5</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(anscombe<span class="sc">$</span>x2,anscombe<span class="sc">$</span>y2,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">main=</span><span class="st">"Conjunto de datos 2"</span>,<span class="at">cex=</span><span class="fl">1.25</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y2<span class="sc">~</span>x2,<span class="at">data=</span>anscombe),<span class="at">col=</span><span class="st">"red"</span>,<span class="at">lwd=</span><span class="fl">1.5</span>)</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(anscombe<span class="sc">$</span>x3,anscombe<span class="sc">$</span>y3,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">main=</span><span class="st">"Conjunto de datos 3"</span>,<span class="at">cex=</span><span class="fl">1.25</span>)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y3<span class="sc">~</span>x3,<span class="at">data=</span>anscombe),<span class="at">col=</span><span class="st">"red"</span>,<span class="at">lwd=</span><span class="fl">1.5</span>)</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(anscombe<span class="sc">$</span>x4,anscombe<span class="sc">$</span>y4,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">main=</span><span class="st">"Conjunto de datos 4"</span>,<span class="at">cex=</span><span class="fl">1.25</span>)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="fu">lm</span>(y4<span class="sc">~</span>x4,<span class="at">data=</span>anscombe),<span class="at">col=</span><span class="st">"red"</span>,<span class="at">lwd=</span><span class="fl">1.5</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" style="width:90.0%"></p>
</div>
</div>
<p>Ejemplos más espectaculares se pueden obtener con las funciones del paquete <strong>datasaurus</strong>, que permiten crear conjuntos de puntos de “formas” diferentes con los mismos estadísticos, y en particular la misma correlación. Empleando este paquete, hemos creado dos pares de vectores de datos <code>dino</code> y <code>star</code>, que hemos recogido en la siguiente <a href="https://github.com/AprendeR-UIB/MatesII/blob/master/Dades/Datasaurus.txt">tabla de datos</a>. Esta tabla de datos tiene tres variables: una variable <code>dataset</code> que indica el conjunto de datos, y las variables <code>x</code> e <code>y</code> que dan las coordenadas de los puntos que forman cada conjunto de datos. Comprobaremos que los dos pares de vectores de datos tienen el mismo coeficiente de correlación (al menos hasta la séptima cifra decimal) y los dibujaremos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>datasaure<span class="ot">=</span><span class="fu">read.table</span>(<span class="st">"https://raw.githubusercontent.com/AprendeR-UIB/MatesII/master/Dades/Datasaurus.txt"</span>,<span class="at">header=</span><span class="cn">TRUE</span>,<span class="at">sep=</span><span class="st">"</span><span class="sc">\t</span><span class="st">"</span>)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(datasaure)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   284 obs. of  3 variables:
 $ dataset: chr  "dino" "dino" "dino" "dino" ...
 $ x      : num  55.4 51.5 46.2 42.8 40.8 ...
 $ y      : num  97.2 96 94.5 91.4 88.3 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>dino<span class="ot">=</span>datasaure[datasaure<span class="sc">$</span>dataset<span class="sc">==</span><span class="st">"dino"</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>star<span class="ot">=</span>datasaure[datasaure<span class="sc">$</span>dataset<span class="sc">==</span><span class="st">"star"</span>,<span class="dv">2</span><span class="sc">:</span><span class="dv">3</span>]</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(dino<span class="sc">$</span>x,dino<span class="sc">$</span>y)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.0629611</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(star<span class="sc">$</span>x,star<span class="sc">$</span>y)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.0629611</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(dino,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span><span class="fl">1.25</span>)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(star,<span class="at">pch=</span><span class="dv">20</span>,<span class="at">cex=</span><span class="fl">1.25</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-fig.asp="0.5">
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" style="width:90.0%"></p>
</div>
</div>
<p>Ahora supongamos que tenemos una tabla de datos numéricos de la forma <span class="math display">\[
\begin{array}{cccc}
X_1 &amp; X_2 &amp; \ldots &amp; X_p\\ \hline
x_{1 1} &amp; x_{1 2} &amp;\ldots &amp; x_{1 p}\\
x_{2 1} &amp; x_{2 2} &amp;\ldots &amp; x_{2 p}\\
\vdots &amp; \vdots   &amp;   \ddots    &amp;\vdots\\
x_{n 1} &amp; x_{n 2} &amp;\ldots &amp; x_{n p}
\end{array}
\]</span></p>
<p>donde cada columna representa los valores de cierta variable <span class="math inline">\(X_i\)</span> y cada fila un individuo de una muestra de la población, de forma que la entrada <span class="math inline">\(x_{ij}\)</span> de esta tabla es el valor de <span class="math inline">\(X_j\)</span> sobre el individuo <span class="math inline">\(i\)</span>-ésimo de la muestra.</p>
<p>Su <em>matriz de correlaciones de Pearson</em> es la matriz simétrica <span class="math display">\[
\begin{pmatrix}  
1 &amp; R_{X_1,X_2} &amp; \ldots &amp; R_{X_1,X_p}\\
R_{X_2,X_1} &amp; 1 &amp; \ldots &amp; R_{X_2,X_p}\\
  \vdots &amp; \vdots  &amp;  \ddots      &amp; \vdots\\
R_{X_p,X_1} &amp; R_{X_p,X_2} &amp; \ldots &amp; 1
\end{pmatrix}
\]</span></p>
<p>Esta matriz de correlaciones se calcula con la función <code>cor</code> aplicada a la matriz o el data frame de variables numéricas que almacena la tabla de datos. Por ejemplo, la matriz de correlaciones de Pearson de la tabla de datos <code>DF</code> del Ejemplo que venimos trabajando es</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(DF)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>            BMI       Chol        Edad
BMI  1.00000000  0.6979141  0.07316517
Chol 0.69791406  1.0000000 -0.33145274
Edad 0.07316517 -0.3314527  1.00000000</code></pre>
</div>
</div>
</section>
<section id="estimación" class="level3" data-number="2.4.3">
<h3 data-number="2.4.3" class="anchored" data-anchor-id="estimación"><span class="header-section-number">2.4.3</span> Estimación</h3>
<p>Las covarianzas de dos vectores obtenidos midiendo dos variables <span class="math inline">\(X,Y\)</span> sobre una muestra aleatoria simple de sujetos de una población estiman la covarianza poblacional de las variables <span class="math inline">\(X,Y\)</span> que han producido los vectores:</p>
<ul>
<li><p>La covarianza muestral <span class="math inline">\(\widetilde{S}_{X,Y}\)</span> siempre es un estimador no sesgado de la covarianza poblacional <span class="math inline">\(\sigma_{X,Y}\)</span></p></li>
<li><p>La covarianza <span class="math inline">\({S}_{X,Y}=\frac{n-1}{n}\widetilde{S}_{X,Y}\)</span> es un estimador sesgado de la covarianza poblacional <span class="math inline">\(\sigma_{X,Y}\)</span>, con sesgo que tiende a 0, y es más eficiente que <span class="math inline">\(\widetilde{S}_{X,Y}\)</span></p></li>
<li><p>La covarianza <span class="math inline">\(S_{X,Y}\)</span> es el estimador máximo verosímil de <span class="math inline">\(\sigma_{X,Y}\)</span> cuando la distribución conjunta de las variables <span class="math inline">\(X,Y\)</span> es la <a href="https://es.wikipedia.org/wiki/Distribuci%C3%B3n_normal_multivariada">normal bivariante</a> que estudiaremos próximamente.</p></li>
</ul>
<p>La correlación de Pearson de dos vectores obtenidos midiendo dos variables continuas <span class="math inline">\(X,Y\)</span> sobre una muestra aleatoria simple de sujetos de una población estima la correlación poblacional de las variables <span class="math inline">\(X,Y\)</span>. En concreto:</p>
<ul>
<li><span class="math inline">\(R_{X,Y}\)</span> es un estimador máximo verosímil de <span class="math inline">\(\rho_{X,Y}\)</span> cuando la distribución conjunta de <span class="math inline">\(X,Y\)</span> se normal bivariante. se un estimador sesgado, pero su sesgo tiende a 0.</li>
</ul>
</section>
<section id="correlación-de-spearman" class="level3" data-number="2.4.4">
<h3 data-number="2.4.4" class="anchored" data-anchor-id="correlación-de-spearman"><span class="header-section-number">2.4.4</span> Correlación de Spearman</h3>
<p>La correlación de Pearson mide específicamente la tendencia de dos variables continuas a depender linealmente la una de la otra. Si no esperamos que esta dependencia lineal exista, o si nuestras variables son discretas o simplemente ordinales, emplear la correlación de Pearson para analizar la relación entre dos variables no es lo más adecuado. Entre las propuestas alternativas, la más popular es la <strong>correlación de Spearman</strong>.</p>
<p>Intuitivamente, la correlación de Spearman mide la tendencia que si <span class="math inline">\(x_i&gt;x_j\)</span>, pase que <span class="math inline">\(y_i&gt;y_j\)</span>. Su valor es 1 si, para todos <span class="math inline">\(y,j\)</span>, <span class="math display">\[
x_i&gt;x_j\Longleftrightarrow y_i&gt;y_j
\]</span> y su valor es -1 si, para todo <span class="math inline">\(i,j\)</span>, <span class="math display">\[
x_i&gt;x_j\Longleftrightarrow y_i&lt;y_j
\]</span> Cuanto más se acerca la correlación de Spearman a 1 (o -1), para más parejas de índices <span class="math inline">\((i,j)\)</span> tales que <span class="math inline">\(x_i&gt;x_j\)</span> se tiene que <span class="math inline">\(y_i&gt;y_j\)</span> (<span class="math inline">\(y_i&lt;y_j\)</span>, si se acerca a -1).</p>
<p>Formalmente, la correlación de Spearman de dos vectores <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> se define como la correlación de Pearson de los vectores de <strong>rangos</strong> de <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span>. El vector de rangos de un vector <span class="math inline">\(X\)</span> se obtiene sustituyendo cada valor de <span class="math inline">\(X\)</span> por su posición en el vector ordenado de menor a mayor, y en caso de empates asignando a grupos de valores empatados la media de las posiciones que ocuparían. Por ejemplo, el vector de rangos de</p>
<p><span class="math display">\[
x=(4,5,1,5,1,3,4,4)
\]</span> es <span class="math display">\[
(5,7.5,1.5,7.5,1.5,3,5,5)
\]</span> ¿Cómo hemos calculado este vector?</p>
<ol type="1">
<li>Primero asignamos a cada valor del vector su posición si estuvieran ordenados de menor a mayor, y en caso de empate por ahora los ordenaremos de izquierda a derecha: <span class="math display">\[
\begin{array}{r|cccccccc}
x &amp; 4&amp; 5 &amp; 1 &amp; 5 &amp; 1 &amp; 3 &amp; 4 &amp; 4\\ \hline
\text{Posició} &amp; 4 &amp; 7 &amp; 1 &amp; 8 &amp; 2 &amp; 3 &amp; 5 &amp; 6\\
\end{array}
\]</span></li>
<li>Ahora, para asignar los rangos finales:</li>
</ol>
<ul>
<li>El rango de los dos elementos 1 de <span class="math inline">\(x\)</span> es la media de las posiciones 1, 2 del vector ordenado: 1.5.</li>
<li>Como que solo hay un 3 en <span class="math inline">\(x\)</span>, su rango es su posición en el vector ordenado: 3.</li>
<li>El rango de los tres elementos 4 es la media de las posiciones 4, 5 y 6 del vector ordenado: 5.</li>
<li>Finalmente, el rango de los dos elementos 5 es la media de las posiciones 7, 8 del vector ordenado: 7.5.</li>
</ul>
<p><span class="math display">\[
\begin{array}{r|cccccccc}
x &amp; 4&amp; 5 &amp; 1 &amp; 5 &amp; 1 &amp; 3 &amp; 4 &amp; 4\\ \hline
\text{Posició} &amp; 4 &amp; 7 &amp; 1 &amp; 8 &amp; 2 &amp; 3 &amp; 5 &amp; 6\\ \hline
\text{Rang} &amp; 5 &amp; 7.5 &amp; 1.5 &amp; 7.5 &amp; 1.5 &amp; 3 &amp; 5 &amp; 5
\end{array}
\]</span></p>
<p>Por cierto, con R el vector de rangos se calcula con la función <code>rank</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rank</span>(<span class="fu">c</span>(<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">1</span>,<span class="dv">5</span>,<span class="dv">1</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">4</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.0 7.5 1.5 7.5 1.5 3.0 5.0 5.0</code></pre>
</div>
</div>
<p>Con R, la correlación de Spearman se calcula directamente con la función <code>cor</code> especificando el parámetro <code>method="spearman"</code>. (El valor por defecto del parámetro <code>method</code> es <code>"pearson"</code> y por eso no lo indicamos cuando calculamos la correlación de Pearson.)</p>
<p><span style="color: blue;"><em>Ejemplo</em></span> Consideremos los vectores <code>BMI</code> y <code>Chol</code> del ejemplo que venimos trabajando. Lo primero que haremos será calcular sus vectores de rangos:</p>
<p><span class="math display">\[
\begin{array}{|c|c||c|c|}
\hline
BMI &amp; \text{Rangs} &amp; Chol&amp;  \text{Rangs}
\\\hline\hline
18.3&amp; 1 &amp; 170&amp; 1 \\
24.4&amp;4.5 &amp; 202 &amp; 2\\
24.6&amp;6 &amp; 215&amp; 5 \\
24.4&amp;4.5 &amp; 218&amp;  6\\
22.2&amp;3 &amp; 210&amp;  3.5\\
19.5&amp;2 &amp; 210&amp;  3.5\\\hline
\end{array}
\]</span></p>
<p>Por tanto, la correlación de Spearman de <span class="math display">\[
\mathit{BMI}=(18.3, 24.4, 24.6, 24.4, 22.2, 19.5)\mbox{ i }\mathit{Chol}=(170, 202, 215, 218, 210, 210)
\]</span> es la correlación de Pearson de <span class="math display">\[
(1, 4.5, 6, 4.5, 3, 2)\mbox{ i }(1, 2, 5, 6, 3.5, 3.5)
\]</span></p>
<p>Comprobémoslo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(BMI,Chol,<span class="at">method=</span><span class="st">"spearman"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6470588</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="fl">4.5</span>,<span class="dv">6</span>,<span class="fl">4.5</span>,<span class="dv">3</span>,<span class="dv">2</span>),<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="fl">3.5</span>,<span class="fl">3.5</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.6470588</code></pre>
</div>
</div>
</section>
</section>
<section id="contrastes-de-correlación" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="contrastes-de-correlación"><span class="header-section-number">2.5</span> Contrastes de correlación</h2>
<p>En un <em>contraste de correlación</em> de dos variables poblacionales continuas <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span>, la hipótesis nula es que no hay correlación entre las dos variables, lo cual traduce que no hay ninguna relación entre ellas. <span class="math display">\[
\left\{
\begin{array}{ll}
H_0: &amp; \rho_{XY}=0\\
H_1: &amp; \rho_{XY}&gt; 0\text{ o }\rho_{XY}&lt; 0\text{ o }\rho_{XY}\neq 0
\end{array}\right.
\]</span></p>
<blockquote class="blockquote">
<p>Si en un contraste de correlación rechazamos la hipótesis nula, en particular concluimos que las variables <span class="math inline">\(X\)</span> e <span class="math inline">\(Y\)</span> son dependientes (porque si fueran independientes, su correlación seria 0).</p>
</blockquote>
<p>No explicaremos cómo se hace a mano este contraste ni qué hipótesis tienen que satisfacer las variables poblacionales para que el resultado sea fiable. Si estáis interesados en el detalle, podéis consultar la <a href="https://en.wikipedia.org/wiki/pearson_correlation_coefficient#Testing_using_Student's_t-distribution">correspondiente entrada de la Wikipedia</a>. Simplemente tenéis que saber que se efectúa con la función <code>cor.plot</code>. Su sintaxis es similar a la de las otras funciones que efectúan contrastes.</p>
<p><span style="color: blue;"><em>Ejemplo</em></span> Queremos contrastar si hay correlación positiva entre el BMI y el nivel de colesterol de un adulto sano, con un nivel de significación del 5%.</p>
<p><em>Variables poblacionales de interés</em>:</p>
<ul>
<li><span class="math inline">\(\mathit{BMI}\)</span>: “Tomamos un adulto sano y anotamos su BMI”</li>
<li><span class="math inline">\(\mathit{Chol}\)</span>: “Tomamos un adulto sano y anotamos el nivel de colesterol en mg/l”</li>
</ul>
<p><em>Contrast</em>: <span class="math display">\[
\left\{
\begin{array}{ll}
H_0: &amp; \rho_{\textit{BMI,Chol}}=0\\
H_1: &amp; \rho_{\textit{BMI,Chol}}&gt;0
\end{array}\right.
\]</span></p>
<p>Empleamos las muestras de <code>BMI</code> y <code>Chol</code> del Ejemplo que venimos trabajando.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(BMI,Chol,<span class="at">alternative=</span><span class="st">"greater"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  BMI and Chol
t = 1.949, df = 4, p-value = 0.06155
alternative hypothesis: true correlation is greater than 0
95 percent confidence interval:
 -0.08621998  1.00000000
sample estimates:
      cor 
0.6979141 </code></pre>
</div>
</div>
<p><em>Conclusión</em>: No hemos obtenido evidencia estadísticamente significativa que el BMI y el nivel de colesterol de un adulto sano tengan correlación positiva (test de correlación, p-valor 0.06, IC para <span class="math inline">\(\rho\)</span> 95% [-0.086 a 1]).</p>
<p><span style="color: red;"><em>Cuidado</em></span> La conclusión es que no hemos obtenido evidencia que el BMI y el nivel de colesterol <em>tengan correlación positiva</em> <strong>en la población de los adultos sanos</strong>. No en nuestra muestra, que sí que ha dado correlación positiva. Recordad que los contrastes siempre se refieren a la población.</p>
</section>
<section id="gráficos-para-datos-multidimensionales" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="gráficos-para-datos-multidimensionales"><span class="header-section-number">2.6</span> Gráficos para datos multidimensionales</h2>
<section id="otro-gráfico-para-datos-bivariantes" class="level3" data-number="2.6.1">
<h3 data-number="2.6.1" class="anchored" data-anchor-id="otro-gráfico-para-datos-bivariantes"><span class="header-section-number">2.6.1</span> Otro gráfico para datos bivariantes</h3>
<p>El boxplot bivariante es un gráfico de dispersión que incluye dos elipses estimadas, la interior que contiene aproximadamente el 50% de los datos y la exterior que contiene aproximadamente el 95% de los datos. Este tipo de gráficos nos ayuda a localizar datos atípicos. Veamos un ejemplo con los datos de los pingüinos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MVA)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>a2<span class="ot">&lt;-</span> penguins <span class="sc">%&gt;%</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(body_mass_g,bill_length_mm) <span class="sc">%&gt;%</span></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>  na.omit <span class="sc">%&gt;%</span> <span class="fu">as.matrix</span>()</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a><span class="fu">bvbox</span>(a2,<span class="at">xlab =</span> <span class="st">"Peso del pingüino en gr"</span>, </span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a>           <span class="at">ylab =</span> <span class="st">"Longitud del pico en mm"</span>,</span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">pch =</span> <span class="dv">19</span>, <span class="at">cex =</span> <span class="fl">1.25</span>, <span class="at">col =</span> <span class="st">"red"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Las dos rectas dentro de las elipses del gráfico anterior son estimaciones de la recta de regresión.La recta más oscura es la habitual de mínimos cuadrados utilizando todas las observaciones. La recta más clara es una estimación más robusta que reduce la influencia de cualquier valor extremo.</p>
</section>
<section id="matriz-de-dispersión" class="level3" data-number="2.6.2">
<h3 data-number="2.6.2" class="anchored" data-anchor-id="matriz-de-dispersión"><span class="header-section-number">2.6.2</span> Matriz de dispersión</h3>
<p>Es posible ver los gráficos de dispersión por pares entre diversas variables cuantitativas utilizando una matriz. Se puede generar utilizando la función “pairs()” de R base. Veamos un ejemplo con nuestros datos de pingüinos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>a<span class="ot">&lt;-</span>penguins <span class="sc">%&gt;%</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">7</span>) <span class="sc">%&gt;%</span></span>
<span id="cb62-3"><a href="#cb62-3" aria-hidden="true" tabindex="-1"></a>  na.omit</span>
<span id="cb62-4"><a href="#cb62-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb62-5"><a href="#cb62-5" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(a,</span>
<span id="cb62-6"><a href="#cb62-6" aria-hidden="true" tabindex="-1"></a>      <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"blue"</span>)[<span class="fu">as.integer</span>(a<span class="sc">$</span>sex)], </span>
<span id="cb62-7"><a href="#cb62-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">pch =</span> <span class="dv">18</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Existen muchas otras funciones para crear matrices de gráficos de dispersión. Una que nos gusta es <code>ggpairs()</code> del paquete <code>GGally</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(GGally)</span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggpairs</span>(a)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Por defecto, la diagonal principal de la matriz contiene la curva de densidad para cada variable. Por debajo de la diagonal principal se muestran los gráficos de dispersión y la correlación (para las variables cuantitativas) o el cruce entre variables si se trata de una variable categórica.</p>
</section>
<section id="caras-de-chernoff" class="level3" data-number="2.6.3">
<h3 data-number="2.6.3" class="anchored" data-anchor-id="caras-de-chernoff"><span class="header-section-number">2.6.3</span> Caras de Chernoff</h3>
<p>Cada variable del conjunto de datos se usa para representar una característica de la cara. Chernoff usó hasta 18 variables para representar diferentes rasgos faciales como cabeza, nariz, ojos, cejas, boca y orejas. El gráfico de Chernoff tiene como ventaja la facilidad humana para reconocer patrones de caras. El inconveniente es que la representación es muy dependiente de las variables escogidas para representar cada rasgo. Por ejemplo: la boca y la forma de la cabeza son rasgos más llamativos que las orejas o la longitud de la nariz, por tanto, el mismo conjunto puede sugerir distintos patrones de similitud entre las observaciones. Veamos un ejemplo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"aplpack"</span>)</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a>b<span class="ot">&lt;-</span> penguins <span class="sc">%&gt;%</span> </span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>      <span class="fu">filter</span>(species<span class="sc">==</span><span class="st">"Adelie"</span>, </span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a>             island<span class="sc">==</span><span class="st">"Torgersen"</span>,</span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>             sex<span class="sc">==</span><span class="st">"female"</span>,</span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a>             year<span class="sc">==</span><span class="dv">2007</span>)</span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a><span class="fu">faces</span>(b[,<span class="dv">3</span><span class="sc">:</span><span class="dv">6</span>],<span class="at">face.type =</span> <span class="dv">1</span>, <span class="at">scale =</span><span class="cn">TRUE</span>,<span class="at">print.info =</span> <span class="cn">TRUE</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>effect of variables:
 modified item       Var                
 "height of face   " "bill_length_mm"   
 "width of face    " "bill_depth_mm"    
 "structure of face" "flipper_length_mm"
 "height of mouth  " "body_mass_g"      
 "width of mouth   " "bill_length_mm"   
 "smiling          " "bill_depth_mm"    
 "height of eyes   " "flipper_length_mm"
 "width of eyes    " "body_mass_g"      
 "height of hair   " "bill_length_mm"   
 "width of hair   "  "bill_depth_mm"    
 "style of hair   "  "flipper_length_mm"
 "height of nose  "  "body_mass_g"      
 "width of nose   "  "bill_length_mm"   
 "width of ear    "  "bill_depth_mm"    
 "height of ear   "  "flipper_length_mm"</code></pre>
</div>
</div>
<p>Alternativamente, podemos representar cada elemento por una figura geométrica, donde las similitudes entre figuras indican las similitudes entre los elementos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stars</span>(a[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>], <span class="at">key.loc =</span> <span class="fu">c</span>(<span class="dv">44</span>, <span class="fl">1.5</span>),<span class="at">cex=</span><span class="fl">0.45</span>,</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a>      <span class="at">labels=</span><span class="fu">row.names</span>(a[,<span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]), <span class="at">draw.segments=</span><span class="cn">TRUE</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Por supuesto que <code>ggplot2</code> nos da opciones más modernas de este tipo de gráficos. Ver, por ejemplo:</p>
<ul>
<li><p><a href="https://www.r-bloggers.com/2016/10/the-grammar-of-graphics-and-radar-charts/">ggradar</a></p></li>
<li><p><a href="https://www.r-bloggers.com/2023/10/creating-interactive-radar-charts-in-r-with-the-fmsb-library/">fmsb library</a></p></li>
</ul>
</section>
<section id="matriz-de-correlaciones" class="level3" data-number="2.6.4">
<h3 data-number="2.6.4" class="anchored" data-anchor-id="matriz-de-correlaciones"><span class="header-section-number">2.6.4</span> Matriz de correlaciones</h3>
<p>Las correlaciones por pares entre varias variables se muestran visualmente mediante un mapa de calor de la matriz de correlaciones. La función <code>ggcorrplot()</code> del paquete “ggcorrplot” de R puede utilizarse para construirlo. A continuación se muestra un ejemplo que utiliza el conjunto de datos de los pingüinos:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggcorrplot)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>penguins <span class="sc">%&gt;%</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">6</span>) <span class="sc">%&gt;%</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>(.) <span class="sc">%&gt;%</span> </span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cor</span>(.) <span class="sc">%&gt;%</span> </span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggcorrplot</span>(., <span class="at">hc.order =</span> <span class="cn">TRUE</span>,</span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>        <span class="at">type =</span> <span class="st">"lower"</span>,</span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>        <span class="at">colors =</span> <span class="fu">c</span>(<span class="st">"#6D9EC1"</span>,</span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"yellow"</span>, <span class="st">"#E46726"</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>En el gráfico, el color naranja denota correlaciones positivas y el gris correlaciones negativas. Al especificar <code>hc.order</code>,las variables también se ordenan.</p>
</section>
<section id="gráficos-de-mosaico" class="level3" data-number="2.6.5">
<h3 data-number="2.6.5" class="anchored" data-anchor-id="gráficos-de-mosaico"><span class="header-section-number">2.6.5</span> Gráficos de mosaico</h3>
<p>Hasta ahora, hemos explorado métodos para visualizar relaciones entre variables cuantitativas. Pero, ¿qué hacemos si hay más de dos variables categóricas?</p>
<p>Un método consiste en utilizar gráficos de mosaico, en los que las frecuencias de una tabla de contingencia multidimensional se representan mediante regiones rectangulares anidadas que son proporcionales a su frecuencia de celda. La función <code>mosaicplot()</code> de la librería <code>vcd</code> proporciona características más amplias que la de R base.</p>
<p>Si se añade la opción opción <code>shade=TRUE</code> colorea la figura basándose en los residuos estandarizados de un modelo loglineal para la tabla. La idea central detrás de un modelo loglineal es modelar las probabilidades de ocurrencia de cada categoría en la tabla de contingencia y el modelo se ajusta utilizando técnicas de regresión logística.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcd)</span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>a<span class="ot">&lt;-</span> penguins <span class="sc">%&gt;%</span></span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(island,species,sex) <span class="sc">%&gt;%</span></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>a2<span class="ot">&lt;-</span> <span class="fu">table</span>(a)</span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a><span class="fu">mosaicplot</span>(a2,<span class="at">shade=</span><span class="cn">TRUE</span>, <span class="at">main=</span><span class="st">""</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="práctica-3" class="level2" data-number="2.7">
<h2 data-number="2.7" class="anchored" data-anchor-id="práctica-3"><span class="header-section-number">2.7</span> <span style="color: red;"><em>Práctica 3</em></span></h2>
<p>De las fuentes de datos que se citan abajo o de alguna otra fuente que sea de libre acceso, seleccionad un conjunto de datos que os guste y pensad en responder una pregunta a partir de estos. El conjunto de datos debe cumplir con las siguientes condiciones:</p>
<ul>
<li>Que contenga al menos un par de variables cualitativas (una ordinal y otra nominal).</li>
<li>Que contenga al menos cinco variables cuantitativas, cuantas más mejor.</li>
<li>Si tenéis que unir varias tablas de datos, usad las herramientas que hemos presentado de tidyverse.</li>
<li>Algunas fuentes de datos:
<ul>
<li><a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4567555">Compendium of Data Sources for Data Science, Machine Learning, and Artificial Intelligence</a>.</li>
<li><a href="https://datos.gob.es/es/catalogo">datos.gob.es</a></li>
<li><a href="https://ibestat.caib.es/ibestat/inici">IBESTAT</a></li>
<li><a href="https://www.makeovermonday.co.uk/data/">Datasets 2023 Makeover Mondey</a></li>
</ul></li>
</ul>
<ol type="1">
<li><p>Cread un repositorio en Github para vuestro grupo con un nombre que sea fácilmente identificable para los profesores de la asignatura. Cread un proyecto nuevo en RStudio conectado al repositorio anterior que contenga los documentos/scripts y presentación del proyecto.</p></li>
<li><p>El proyecto debe incluir:</p>
<ul>
<li><p>Resumen del problema que trataréis, su contexto y la fuente de datos. Describid cada una de las variables que conforman la base de datos del estudio. Plantead una pregunta u objetivo del proyecto.</p></li>
<li><p>Tibble o dataframe con la base de datos limpia. Indicad los pasos e instrucciones que habéis utilizado para lograr convertir vuestros datos en <code>tidy data</code> (si aplica).</p></li>
<li><p>Un análisis multivariante exploratorio de los datos con visualizaciones apropiadas y su interpretación en el contexto del problema.</p></li>
<li><p>La estimación del vector de medias y la matriz de covarianza/correlación de las variables cuantitativas, así como un contraste de correlación.</p></li>
<li><p>Escribid una conclusión con los resultados importantes del análisis.</p></li>
<li><p>Preparad una presentación de máximo 15 minutos en la que cada miembro del grupo exponga una parte del trabajo.</p></li>
<li><p>Cada grupo tiene 15 minutos para exponer y 5 para responder las dudas y preguntas de los compañeros y de los profesores de la asignatura. La calificación se realizará por medio de la rúbrica publicada en Aula Digital que podéis encontrar en la sección “Bloque I”.</p></li>
<li><p>El peso de la evaluación es el siguiente: 0.8 <span class="math inline">\(\cdot\)</span> Nota de la Exposición + 0.2 <span class="math inline">\(\cdot\)</span> Nota del repositorio$. Para calcular la nota de la Exposición, se tomará la calificación media de vuestros compañeros (excluidos los integrantes del propio grupo) y la asignada por los profesores. Si la diferencia de notas entre los profesores y los compañeros es mayor a 2 puntos, contará únicamente la nota de los profesores.</p></li>
</ul></li>
</ol>
</section>
<section id="distancias" class="level2" data-number="2.8">
<h2 data-number="2.8" class="anchored" data-anchor-id="distancias"><span class="header-section-number">2.8</span> Distancias</h2>
<p>Como hemos mencionado, la información multivariante es una matriz de datos de orden <span class="math inline">\(n \times p\)</span>, con <span class="math inline">\(n\)</span> el número de filas y <span class="math inline">\(p\)</span> el número de variables consideradas. A veces, para determinar cuáles observaciones multivariantes son semejantes y cuáles no, se emplean matrices de distancias o similaridades. Dependiendo del contexto, hay que seleccionar la más apropiada para obtener resultados confiables. A continuación, presentamos algunas de las distancias más utilizadas.</p>
<section id="distancia-euclídea" class="level3" data-number="2.8.1">
<h3 data-number="2.8.1" class="anchored" data-anchor-id="distancia-euclídea"><span class="header-section-number">2.8.1</span> Distancia euclídea</h3>
<p>La distancia euclídea entre dos realizaciones <span class="math inline">\(\underline{X}=(x_1,\ldots,x_p)\)</span> e <span class="math inline">\(\underline{Y}=(y_1,\ldots,y_p)\)</span> se define como</p>
<p><span class="math display">\[d_E(\underline{X},\underline{Y})=\sqrt{\displaystyle\sum_{k=1}^p (x_k-y_k)^2}\]</span></p>
<p>Esta distancia equivale a la suma de las longitudes de los segmentos que unen cada par de posiciones. La siguiente imagen muestra el perfil de dos usuarios en base a las valoraciones que han hecho de 10 ítems.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>usuario_a <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="fl">4.5</span>, <span class="dv">4</span>, <span class="dv">7</span>, <span class="dv">7</span>, <span class="dv">6</span>, <span class="dv">5</span>, <span class="fl">5.5</span>, <span class="dv">5</span>, <span class="dv">6</span>)</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>usuario_b <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="fl">4.5</span>, <span class="dv">4</span>, <span class="dv">7</span>, <span class="dv">7</span>, <span class="dv">6</span>, <span class="dv">5</span>, <span class="fl">5.5</span>, <span class="dv">5</span>, <span class="dv">6</span>) <span class="sc">+</span> <span class="dv">3</span></span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">usuario =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"a"</span>, <span class="st">"b"</span>), <span class="at">each =</span> <span class="dv">10</span>),</span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a>                    <span class="at">valoracion =</span> <span class="fu">c</span>(usuario_a, usuario_b),</span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">item =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> datos, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(item), <span class="at">y =</span> valoracion,</span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a>                         <span class="at">colour =</span> usuario)) <span class="sc">+</span></span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>(<span class="fu">aes</span>(<span class="at">group =</span> usuario)) <span class="sc">+</span></span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">group =</span> item), <span class="at">colour =</span> <span class="st">"firebrick"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"item"</span>) <span class="sc">+</span></span>
<span id="cb69-13"><a href="#cb69-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La distancia euclideana entre los dos usuarios es:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">sum</span>((usuario_a<span class="sc">-</span>usuario_b)<span class="sc">^</span><span class="dv">2</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 9.486833</code></pre>
</div>
</div>
<p>Las funciones <code>dist()</code> de R base y <code>get_dist</code> de la librería <code>factoextra</code> se pueden utilizar para calcular las distancias entre todas las filas (observaciones) de una matriz o data frame. Por defecto, las funciones devuelven una matriz triangular inferior.</p>
<p><span style="color: blue;"><em>Ejemplo</em></span>: Para el data frame de los pingüinos, calculamos las distancias euclideanas entre las ocho hembras de la especie Adelie que fueron registradas en Torgensen el año 2007.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>p_ATf<span class="ot">&lt;-</span> penguins <span class="sc">%&gt;%</span> </span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(species<span class="sc">==</span><span class="st">"Adelie"</span>, </span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>         island<span class="sc">==</span><span class="st">"Torgersen"</span>,</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>         sex<span class="sc">==</span><span class="st">"female"</span>,</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a>         year<span class="sc">==</span><span class="dv">2007</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">5</span>)</span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a><span class="fu">dist</span>(p_ATf)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          1         2         3         4         5         6         7
2  9.055385                                                            
3  7.774960  4.318565                                                  
4  5.051732 14.071247 12.291867                                        
5  4.312772 13.030733 11.968709  2.424871                              
6  3.093542 10.664427  8.140025  4.614109  5.412024                    
7  9.176056  1.886796  2.844293 14.052758 13.293607 10.288343          
8  5.568662 12.488795  9.332738  5.441507  7.037755  2.489980 11.825819</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a><span class="fu">get_dist</span>(p_ATf, <span class="at">stand=</span><span class="cn">TRUE</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         1        2        3        4        5        6        7
2 1.819868                                                      
3 3.293836 2.530682                                             
4 1.077437 2.510238 3.181155                                    
5 1.039894 2.343332 3.710845 1.048543                           
6 1.443639 2.415665 2.600833 1.244814 2.113671                  
7 2.840218 1.637506 1.061075 2.989495 3.228280 2.641200         
8 2.750331 3.317954 2.286750 2.271394 3.259136 1.338307 2.850519</code></pre>
</div>
</div>
<p>Las distancias grandes indican mayores disimilitudes entre las observaciones.</p>
<p>Observa que hemos calculado la distancia euclideana con la función <code>get_dist</code> pero estandarizando los datos especificando <code>stand=TRUE</code>, es decir, para cada variable (columna), restamos el valor medio de la columna y dividimos por la desviación típica de la columna, lo cual tiene sentido hacerlo cuando las variables del conjunto de datos están en escalas diferentes. El problema con la distancia euclideana es que no toma en cuenta la correlación entre las variables consideradas.</p>
</section>
<section id="distancia-de-minkowski" class="level3" data-number="2.8.2">
<h3 data-number="2.8.2" class="anchored" data-anchor-id="distancia-de-minkowski"><span class="header-section-number">2.8.2</span> Distancia de Minkowski</h3>
<p>Otra distancia que podría ser considerada es la de Minkowski, cuya definición es la siguiente:</p>
<p><span class="math display">\[d_{M_q}(\underline{X}_i,\underline{X}_j)=\left(\displaystyle\sum_{k=1}^p|x_{ik}-x_{jk}|^q \right)^{1/q}, \;\; q&gt;0\]</span> Presenta los mismos inconvenientes que <span class="math inline">\(d_E\)</span> <span class="math inline">\((d_E = d_{M_2})\)</span>.</p>
<ul>
<li><p>Si <span class="math inline">\(q=1\)</span>, se le llama distancia de Manhattan</p></li>
<li><p>Si <span class="math inline">\(q \rightarrow \infty\)</span>, se le llama distancia dominante <span class="math display">\[d_{M_\infty}(\underline{X}_i,\underline{X}_j)=\max\{ |x_{i1}-x_{j1}|,\ldots,|x_{ip}-y_{jp}|\}\]</span></p></li>
</ul>
<p>La siguiente imagen muestra una comparación entre la distancia euclídea (segmento azul) y la distancia de Manhattan (segmento rojo y verde) en un espacio bidimensional. Existen múltiples caminos para unir dos puntos con el mismo valor de distancia de Manhattan, ya que su valor es igual al desplazamiento total en cada una de las dimensiones.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">observacion =</span> <span class="fu">c</span>(<span class="st">"a"</span>, <span class="st">"b"</span>), <span class="at">x =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">7</span>), <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">7</span>))</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>manhattan <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">x =</span> <span class="fu">rep</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">each =</span> <span class="dv">2</span>),</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">y =</span> <span class="fu">rep</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">each =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="dv">5</span>),</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">xend =</span> <span class="fu">rep</span>(<span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">each =</span> <span class="dv">2</span>) <span class="sc">+</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">1</span>), <span class="dv">5</span>),</span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>              <span class="at">yend =</span> <span class="fu">rep</span>(<span class="dv">3</span><span class="sc">:</span><span class="dv">7</span>, <span class="at">each =</span> <span class="dv">2</span>))</span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>manhattan_2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>                <span class="at">x =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">7</span>),</span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>                <span class="at">y =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">4</span>),</span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>                <span class="at">xend =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">7</span>),</span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>                <span class="at">yend =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">7</span>))</span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> datos, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y)) <span class="sc">+</span></span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">x =</span> <span class="dv">2</span>, <span class="at">y =</span> <span class="dv">2</span>, <span class="at">xend =</span> <span class="dv">7</span>, <span class="at">yend =</span> <span class="dv">7</span>), <span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb76-16"><a href="#cb76-16" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_segment</span>(<span class="at">data =</span> manhattan, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">xend =</span> xend, <span class="at">yend =</span> yend),</span>
<span id="cb76-17"><a href="#cb76-17" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb76-18"><a href="#cb76-18" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_segment</span>(<span class="at">data =</span> manhattan_2, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">xend =</span> xend, <span class="at">yend =</span> yend),</span>
<span id="cb76-19"><a href="#cb76-19" aria-hidden="true" tabindex="-1"></a>             <span class="at">color =</span> <span class="st">"green3"</span>, <span class="at">size =</span> <span class="fl">1.2</span>) <span class="sc">+</span></span>
<span id="cb76-20"><a href="#cb76-20" aria-hidden="true" tabindex="-1"></a><span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span></span>
<span id="cb76-21"><a href="#cb76-21" aria-hidden="true" tabindex="-1"></a><span class="fu">theme</span>(<span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb76-22"><a href="#cb76-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">panel.grid.major =</span> <span class="fu">element_line</span>(<span class="at">size =</span> <span class="dv">2</span>),</span>
<span id="cb76-23"><a href="#cb76-23" aria-hidden="true" tabindex="-1"></a>      <span class="at">panel.background =</span> <span class="fu">element_rect</span>(<span class="at">fill =</span> <span class="st">"gray"</span>,</span>
<span id="cb76-24"><a href="#cb76-24" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">colour =</span> <span class="st">"white"</span>,</span>
<span id="cb76-25"><a href="#cb76-25" aria-hidden="true" tabindex="-1"></a>                                      <span class="at">size =</span> <span class="fl">0.5</span>, <span class="at">linetype =</span> <span class="st">"solid"</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
<section id="distancias-basadas-en-la-correlación" class="level2" data-number="2.9">
<h2 data-number="2.9" class="anchored" data-anchor-id="distancias-basadas-en-la-correlación"><span class="header-section-number">2.9</span> Distancias basadas en la correlación</h2>
<p>Las distancias basadas en la correlación son útiles utilizadas cuando la similitud queremos establecerla en términos del patrón o forma y no de desplazamiento o magnitud; por ejemplo en el análisis de datos de expresión génica.</p>
<p><span class="math display">\[d_{cor}(\underline{X}_i,\underline{X}_j)=1-Cor(\underline{X}_i,\underline{X}_j)\]</span></p>
<p>donde la correlación puede ser de distintos tipos (Pearson, Spearman, Kendall…)</p>
<p>En la siguiente imagen mostramos el perfil de 3 usuarios. Veamos qué ocurre si utilizamos la distancia euclideana y la de correlación de Pearson para compararlos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>usuario_a <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="fl">4.5</span>, <span class="dv">4</span>, <span class="fl">7.5</span>, <span class="dv">7</span>, <span class="dv">6</span>, <span class="dv">5</span>, <span class="fl">5.5</span>, <span class="dv">5</span>, <span class="dv">6</span>)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>usuario_b <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="fl">4.5</span>, <span class="dv">4</span>, <span class="fl">7.5</span>, <span class="dv">7</span>, <span class="dv">6</span>, <span class="dv">5</span>, <span class="fl">5.5</span>, <span class="dv">5</span>, <span class="dv">6</span>) <span class="sc">+</span> <span class="dv">4</span></span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a>usuario_c <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="fl">5.5</span>, <span class="fl">4.8</span>, <span class="fl">5.4</span>, <span class="fl">4.7</span>, <span class="fl">5.6</span>, <span class="fl">5.3</span>, <span class="fl">5.5</span>, <span class="fl">5.2</span>, <span class="fl">4.8</span>)</span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">usuario =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"a"</span>, <span class="st">"b"</span>, <span class="st">"c"</span>), <span class="at">each =</span> <span class="dv">10</span>),</span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a>                    <span class="at">valoracion =</span> <span class="fu">c</span>(usuario_a, usuario_b, usuario_c),</span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a>                    <span class="at">item =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>)</span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> datos, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(item),</span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a>                         <span class="at">y =</span> valoracion, </span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a>                         <span class="at">colour =</span> usuario)) <span class="sc">+</span></span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_path</span>(<span class="fu">aes</span>(<span class="at">group =</span> usuario)) <span class="sc">+</span></span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb77-14"><a href="#cb77-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"item"</span>) <span class="sc">+</span></span>
<span id="cb77-15"><a href="#cb77-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span></span>
<span id="cb77-16"><a href="#cb77-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dist</span>(<span class="at">x =</span> <span class="fu">rbind</span>(usuario_a, usuario_b, usuario_c), <span class="at">method =</span> <span class="st">"euclidean"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          usuario_a usuario_b
usuario_b  12.64911          
usuario_c   3.75100  13.98821</code></pre>
</div>
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="dv">1</span> <span class="sc">-</span> <span class="fu">cor</span>(<span class="at">x =</span> <span class="fu">cbind</span>(usuario_a, usuario_b, usuario_c), <span class="at">method =</span> <span class="st">"pearson"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          usuario_a usuario_b usuario_c
usuario_a 0.0000000 0.0000000 0.9466303
usuario_b 0.0000000 0.0000000 0.9466303
usuario_c 0.9466303 0.9466303 0.0000000</code></pre>
</div>
</div>
<p>De acuerdo a la distancia euclideana, los usuarios a y c son los más similares, mientras que acorde a la correlación de Pearson, a y b son los más parecidos. Este ejemplo pone de manifiesto que no existe una única medida de distancia que sea mejor que las demás, sino que, dependiendo del contexto, una será más adecuada que otra.</p>
</section>
<section id="distancia-de-mahalanobis" class="level2" data-number="2.10">
<h2 data-number="2.10" class="anchored" data-anchor-id="distancia-de-mahalanobis"><span class="header-section-number">2.10</span> Distancia de Mahalanobis</h2>
<p><span class="math display">\[d^2_M \left( \underline{X}_i,\underline{X}_j \right)= \left(\underline{X}_i-\underline{X}_j \right)^t {\bf S}^{-1}
\left(\underline{X}_i-\underline{X}_j\right),\]</span></p>
<p>donde <span class="math inline">\({\bf S}\)</span> es la matriz de covarianzas muestrales de la matriz de datos <span class="math inline">\({\bf X}\)</span>.</p>
<p>Es adecuada como medida de discrepancia entre datos, porque:</p>
<ul>
<li><p>Es invariante frente a transformaciones lineales invertibles de las variables.</p></li>
<li><p><span class="math inline">\(d_E=d_M\)</span> cuando <span class="math inline">\({\bf S}={\bf I}\)</span> y <span class="math inline">\(d_K = d_M\)</span> cuando <span class="math inline">\({\bf S}=diag(s^2_1,\ldots,s^2_p),\)</span></p></li>
<li><p>Esta distancia tiene en cuenta las correlaciones entre las variables.</p></li>
<li><p>No aumenta por el simple hecho de aumentar el número de variables registradas, sino que solamente aumentará cuando las nuevas variables no sean redundantes con respecto de la información aportada por las anteriores.</p></li>
<li><p>Esta es la distancia más utilizada cuando todas las variables son cuantitativas.</p></li>
</ul>
</section>
<section id="distancias-para-variables-binarias" class="level2" data-number="2.11">
<h2 data-number="2.11" class="anchored" data-anchor-id="distancias-para-variables-binarias"><span class="header-section-number">2.11</span> Distancias para variables binarias:</h2>
<p>Si <span class="math inline">\(X_1,\ldots,X_p\)</span> son variables que toman valores <span class="math inline">\(\{0,1\}\)</span>, existen muchos <strong>coeficientes de similaridad</strong> <span class="math inline">\(s_{ij}\)</span> entre dos observaciones <span class="math inline">\(i,j\)</span>, calculados a partir de las frecuencias tales que <span class="math inline">\(a+b+c+d=p\)</span>, donde:</p>
<ul>
<li><p><span class="math inline">\(a\)</span>: el número de variables con respuesta 1 en ambos individuos,</p></li>
<li><p><span class="math inline">\(b\)</span>: el número de variables con respuesta 0 en la observación <span class="math inline">\(i\)</span> y con respuesta 1 en el individuo <span class="math inline">\(j\)</span>,</p></li>
<li><p><span class="math inline">\(c\)</span>: el número de variables con respuesta 1 en la observación <span class="math inline">\(i\)</span> y con respuesta 0 en la observación <span class="math inline">\(j\)</span>,</p></li>
<li><p><span class="math inline">\(d\)</span>: el número de variables con respuesta 0 en ambos individuos.</p></li>
</ul>
<p>Algunos coeficientes de similaridad son:</p>
<p><strong>Sokal y Michener</strong>: <span class="math inline">\(s_{ij}=\frac{a+d}{p}\)</span>, <strong>Jaccard</strong>: <span class="math inline">\(s_{ij} =\frac{a}{a+b+c}\)</span></p>
<p>Aplicando uno de estos coeficientes a un conjunto de <span class="math inline">\(n\)</span> objetos se obtiene una matriz de similaridades <span class="math inline">\({\bf S}=(s_{ij})_{n\times n}\)</span></p>
<p><span style="color: blue;"><em>Ejemplo</em></span>: Se han medido 6 variables sobre 3 individuos:</p>
<table class="table">
<thead>
<tr class="header">
<th>ind.</th>
<th><span class="math inline">\(X_1\)</span></th>
<th><span class="math inline">\(X_2\)</span></th>
<th><span class="math inline">\(X_3\)</span></th>
<th><span class="math inline">\(X_4\)</span></th>
<th><span class="math inline">\(X_5\)</span></th>
<th><span class="math inline">\(X_6\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>2</td>
<td>1</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td>3</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/tabla_binaria.PNG" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Las matrices de similaridad son: <span class="math display">\[{\bf S}_{Sokal}=\left(\begin{array}{ccc}
1 &amp; 0.6667 &amp; 0.5\\
0.667 &amp; 1 &amp; 0.5\\
0.5 &amp; 0.5 &amp; 1
\end{array}\right), \;\;\; {\bf S}_{Jaccard}=\left(\begin{array}{ccc}
1 &amp; 0.6 &amp; 0.4\\
0.6 &amp; 1 &amp; 0.4\\
0.4 &amp; 0.4 &amp; 1
\end{array}\right) \]</span></p>
</section>
<section id="distancias-para-variables-categóricas" class="level2" data-number="2.12">
<h2 data-number="2.12" class="anchored" data-anchor-id="distancias-para-variables-categóricas"><span class="header-section-number">2.12</span> Distancias para variables categóricas:</h2>
<p>Se mide una variable categórica nominal con <span class="math inline">\(k\)</span> niveles sobre una muestra de <span class="math inline">\(n = n_1+\cdots+n_g\)</span> observaciones provenientes de <span class="math inline">\(g\)</span> poblaciones diferentes. Se desea obtener una medida de disimilaridad entre estas poblaciones.</p>
<p>En estas condiciones, el vector de frecuencias de cada población <span class="math inline">\({\bf n}_{\alpha}=(n_{\alpha1},\ldots,n_{\alpha k})\)</span>, para <span class="math inline">\(\alpha=1,\ldots, g\)</span>, tiene una distribución conjunta multinomial con parámetros <span class="math inline">\((n_{\alpha}, {\bf p}_{\alpha})\)</span>, donde <span class="math inline">\(n_{\alpha}=n_{\alpha1}+\ldots +n_{\alpha k}\)</span> y <span class="math inline">\({\bf p}_{\alpha}=(p_{\alpha 1},\ldots,p_{\alpha k}\)</span> es el vector de probabilidades de los <span class="math inline">\(k\)</span> niveles en la población <span class="math inline">\(\alpha\)</span> (con <span class="math inline">\(p_{\alpha 1}+\ldots + p_{\alpha k}=1\)</span>).</p>
<p><span style="color: blue;"><em>Ejemplo</em></span>: La siguiente tabla contiene las proporciones génicas observadas entre 10 poblaciones. Observa que las filas suman 1.</p>
<table class="table">
<thead>
<tr class="header">
<th>Población</th>
<th>grupo A</th>
<th>grupo AB</th>
<th>grupo B</th>
<th>grupo O</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>francesa</td>
<td>0.21</td>
<td>0.06</td>
<td>0.06</td>
<td>0.67</td>
</tr>
<tr class="even">
<td>checa</td>
<td>0.25</td>
<td>0.04</td>
<td>0.14</td>
<td>0.57</td>
</tr>
<tr class="odd">
<td>germánica</td>
<td>0.22</td>
<td>0.06</td>
<td>0.08</td>
<td>0.64</td>
</tr>
<tr class="even">
<td>vasca</td>
<td>0.19</td>
<td>0.04</td>
<td>0.02</td>
<td>0.75</td>
</tr>
<tr class="odd">
<td>china</td>
<td>0.18</td>
<td>0.00</td>
<td>0.15</td>
<td>0.67</td>
</tr>
<tr class="even">
<td>ainu</td>
<td>0.23</td>
<td>0.00</td>
<td>0.28</td>
<td>0.49</td>
</tr>
<tr class="odd">
<td>esquimal</td>
<td>0.30</td>
<td>0.00</td>
<td>0.06</td>
<td>0.64</td>
</tr>
<tr class="even">
<td>negra USA</td>
<td>0.10</td>
<td>0.06</td>
<td>0.13</td>
<td>0.71</td>
</tr>
<tr class="odd">
<td>española</td>
<td>0.27</td>
<td>0.04</td>
<td>0.06</td>
<td>0.63</td>
</tr>
<tr class="even">
<td>egipcia</td>
<td>0.21</td>
<td>0.05</td>
<td>0.20</td>
<td>0.54</td>
</tr>
</tbody>
</table>
<p>Dos medidas de disimilaridad para este tipo de variables son:</p>
<ul>
<li><p><strong>Distancia de Bhattacharyya</strong> <span class="math display">\[d^2_{ij}=arccos\left( \displaystyle\sum_{l=1}^k \sqrt{p_{il} \; p_{jl}}\right)\]</span></p></li>
<li><p><strong>Distancia de Balakrishnan-Sanghvi</strong> <span class="math display">\[d^2_{ij}= 2 \displaystyle\sum_{l=1}^k \frac{(p_{il}-p_{jl})^2}{p_{il}+p_{jl}} \]</span></p></li>
</ul>
<p>Para los datos del ejemplo, la matriz de distancias de Bhattacharyya es:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>poblacion<span class="ot">=</span><span class="fu">c</span>(<span class="st">"francesa"</span>,<span class="st">"checa"</span>,<span class="st">"germánica"</span>,<span class="st">"vasca"</span>,<span class="st">"china"</span>,<span class="st">"ainu"</span>,<span class="st">"esquimal"</span>,<span class="st">"negra USA"</span>,<span class="st">"española"</span>,<span class="st">"egipcia"</span>)</span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>grupoA<span class="ot">=</span><span class="fu">c</span>(<span class="fl">0.21</span>,<span class="fl">0.25</span>,.<span class="dv">22</span>,.<span class="dv">19</span>,.<span class="dv">18</span>,.<span class="dv">23</span>,.<span class="dv">3</span>,.<span class="dv">1</span>,.<span class="dv">27</span>,.<span class="dv">21</span>)</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a>grupoAB<span class="ot">=</span><span class="fu">c</span>(.<span class="dv">06</span>,.<span class="dv">04</span>,.<span class="dv">06</span>,.<span class="dv">04</span>,.<span class="dv">00</span>,.<span class="dv">00</span>,.<span class="dv">00</span>,.<span class="dv">06</span>,.<span class="dv">04</span>,.<span class="dv">05</span>)</span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>grupoB<span class="ot">=</span><span class="fu">c</span>(.<span class="dv">06</span>,.<span class="dv">14</span>,.<span class="dv">08</span>,.<span class="dv">02</span>,.<span class="dv">15</span>,.<span class="dv">28</span>,.<span class="dv">06</span>,.<span class="dv">13</span>,.<span class="dv">06</span>,.<span class="dv">2</span>)</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a>grupoO<span class="ot">=</span><span class="fu">c</span>(.<span class="dv">67</span>,.<span class="dv">57</span>,.<span class="dv">64</span>,.<span class="dv">75</span>,.<span class="dv">67</span>,.<span class="dv">49</span>,.<span class="dv">64</span>,.<span class="dv">71</span>,.<span class="dv">63</span>,.<span class="dv">54</span>)</span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a>datos<span class="ot">=</span><span class="fu">data.frame</span>(poblacion,grupoA,grupoAB,grupoB,grupoO)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(philentropy)</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a><span class="fu">distance</span>(datos[,<span class="sc">-</span><span class="dv">1</span>], <span class="at">method =</span> <span class="st">"bhattacharyya"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              v1          v2           v3          v4         v5         v6
v1  0.0000000000 0.012324966 0.0009483429 0.007777165 0.04156128 0.08081738
v2  0.0123249656 0.000000000 0.0066949713 0.035943482 0.02529075 0.03431210
v3  0.0009483429 0.006694971 0.0000000000 0.013834658 0.03731750 0.06762516
v4  0.0077771654 0.035943482 0.0138346582 0.000000000 0.05279229 0.11642553
v5  0.0415612774 0.025290748 0.0373174959 0.052792291 0.00000000 0.01879186
v6  0.0808173801 0.034312099 0.0676251647 0.116425530 0.01879186 0.00000000
v7  0.0347713474 0.030975271 0.0343982089 0.034376078 0.01808704 0.04888218
v8  0.0172057129 0.022070358 0.0157266766 0.032991841 0.03716560 0.07012655
v9  0.0032054844 0.009334768 0.0030312958 0.011543973 0.03561201 0.06782787
v10 0.0244823653 0.004028694 0.0160452869 0.057509566 0.03136123 0.02962590
            v7         v8          v9         v10
v1  0.03477135 0.01720571 0.003205484 0.024482365
v2  0.03097527 0.02207036 0.009334768 0.004028694
v3  0.03439821 0.01572668 0.003031296 0.016045287
v4  0.03437608 0.03299184 0.011543973 0.057509566
v5  0.01808704 0.03716560 0.035612005 0.031361231
v6  0.04888218 0.07012655 0.067827866 0.029625898
v7  0.00000000 0.06655156 0.020625956 0.052957776
v8  0.06655156 0.00000000 0.030016960 0.020075979
v9  0.02062596 0.03001696 0.000000000 0.024651208
v10 0.05295778 0.02007598 0.024651208 0.000000000</code></pre>
</div>
</div>
<p>Las poblaciones más cercanas (según la distancia de Battacharyya) son la francesa y la germánica con <span class="math inline">\(d_{1,3}=0.00095\)</span>. Mientras que los más alejados son las poblaciones francesa y ainu con <span class="math inline">\(d_{1,6}=0.08082\)</span>.</p>
</section>
<section id="distancias-para-variables-mixtas" class="level2" data-number="2.13">
<h2 data-number="2.13" class="anchored" data-anchor-id="distancias-para-variables-mixtas"><span class="header-section-number">2.13</span> Distancias para variables mixtas</h2>
<p>Cuando disponemos de un conjunto de observaciones sobre variables tanto cuantitativas como cualitativas.</p>
<p>Se define la distancia de Gower como <span class="math inline">\(d^2_{ij}=1-s_{ij}\)</span>, donde <span class="math display">\[s_{ij}=\frac{\sum_{k=1}^{p_1}(1-|x_{ik}-x_{jk}|/G_k)+a+\alpha}{p_1+(p_2-d)+p_3}\]</span> es el coeficiente de similaridad de Gower,</p>
<ul>
<li><p><span class="math inline">\(p_1\)</span> es el número de variables cuantitativas continuas,</p></li>
<li><p><span class="math inline">\(p_2\)</span> es el número de variables binarias,</p></li>
<li><p><span class="math inline">\(p_3\)</span> es el número de variables cualitativas (no binarias),</p></li>
<li><p><span class="math inline">\(a\)</span> es el número de coincidencias (1,1) en las variables binarias,</p></li>
<li><p><span class="math inline">\(d\)</span> es el número de coincidencias (0,0) en las variables binarias,</p></li>
<li><p><span class="math inline">\(\alpha\)</span> es el número de coincidencias en las variables cualitativas (no binarias) y</p></li>
<li><p><span class="math inline">\(G_h\)</span> es el rango de la <span class="math inline">\(k\)</span>-ésima variable cuantitativa.</p></li>
</ul>
<p><span style="color: blue;"><em>Ejemplo</em></span>: Considera 7 variables registradas sobre 50 jugadores de la liga española de fútbol.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="Figuras/tabla_futbol.PNG" class="img-fluid figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p><span class="math inline">\(X_1\)</span> es el número de goles marcados, <span class="math inline">\(X_2\)</span> edad (en años),</p></li>
<li><p><span class="math inline">\(X_3\)</span> altura (m), <span class="math inline">\(X_4\)</span> peso (kg),</p></li>
<li><p><span class="math inline">\(X_5\)</span> pierna buena del jugador (1=drecha, 0=izquierda),</p></li>
<li><p><span class="math inline">\(X_6\)</span> nacionalidad: (1=Argentina, 2=Brasil, 3=Camerun, 4=Italia, 5=España, 6=Francia, 7=Uruguay, 8=Portugal, 9=Inglaterra).</p></li>
<li><p><span class="math inline">\(X_7\)</span> tipo de estudios (1=sin estudios, 2=básicos, 3=medios, 4=superiores)</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>futbol<span class="ot">=</span><span class="fu">read.table</span>(<span class="st">"datos/jugadores.txt"</span>)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(StatMatch)</span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>distancia<span class="ot">=</span><span class="fu">gower.dist</span>(futbol)</span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(distancia,<span class="dv">2</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          [,1]      [,2]      [,3]      [,4]      [,5]      [,6]      [,7]
[1,] 0.0000000 0.2422439 0.4123377 0.3910534 0.3887085 0.2007576 0.3412698
[2,] 0.2422439 0.0000000 0.3331530 0.3317100 0.2575758 0.3510101 0.1863276
          [,8]      [,9]     [,10]     [,11]     [,12]     [,13]     [,14]
[1,] 0.4585137 0.4370491 0.3645382 0.4132395 0.3329726 0.3098846 0.5128066
[2,] 0.3555195 0.3181818 0.2334055 0.2229437 0.2736291 0.1747835 0.3419913
         [,15]     [,16]     [,17]     [,18]     [,19]    [,20]     [,21]
[1,] 0.3879870 0.3872655 0.3910534 0.3324315 0.3823954 0.333153 0.4880952
[2,] 0.3088023 0.2323232 0.2321429 0.1659452 0.2869769 0.463925 0.3930375
         [,22]     [,23]     [,24]     [,25]     [,26]     [,27]     [,28]
[1,] 0.2436869 0.3890693 0.3311688 0.3154762 0.3551587 0.4462482 0.3059163
[2,] 0.3715729 0.2341270 0.2718254 0.4462482 0.2521645 0.2754329 0.4366883
         [,29]     [,30]     [,31]     [,32]     [,33]    [,34]     [,35]
[1,] 0.3977273 0.1803752 0.2561328 0.3612915 0.3450577 0.247114 0.3481241
[2,] 0.2427850 0.3309885 0.1369048 0.2063492 0.2500000 0.403860 0.4788961
         [,36]     [,37]     [,38]     [,39]     [,40]     [,41]     [,42]
[1,] 0.4202742 0.3151154 0.4197330 0.3250361 0.2247475 0.2023810 0.2676768
[2,] 0.2783189 0.1969697 0.3405483 0.2061688 0.3786075 0.4446248 0.1484488
         [,43]     [,44]     [,45]     [,46]     [,47]     [,48]     [,49]
[1,] 0.1801948 0.3403680 0.3762626 0.1524170 0.4889971 0.3986291 0.2987013
[2,] 0.4224387 0.2453102 0.2812049 0.3318903 0.3340548 0.2278139 0.1935426
         [,50]
[1,] 0.4224387
[2,] 0.2516234</code></pre>
</div>
</div>
<p>Con la librería <code>stats</code> de R base puedes calcular la distancia: “euclidean”, “maximum”, “manhattan”, “canberra”, “binary” o “minkowski”.</p>
<p>La función <code>distance()</code>de la libreria <code>philentropy</code> es capaz de calcular 46 diferentes distancias/similaridades.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getDistMethods</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "euclidean"         "manhattan"         "minkowski"        
 [4] "chebyshev"         "sorensen"          "gower"            
 [7] "soergel"           "kulczynski_d"      "canberra"         
[10] "lorentzian"        "intersection"      "non-intersection" 
[13] "wavehedges"        "czekanowski"       "motyka"           
[16] "kulczynski_s"      "tanimoto"          "ruzicka"          
[19] "inner_product"     "harmonic_mean"     "cosine"           
[22] "hassebrook"        "jaccard"           "dice"             
[25] "fidelity"          "bhattacharyya"     "hellinger"        
[28] "matusita"          "squared_chord"     "squared_euclidean"
[31] "pearson"           "neyman"            "squared_chi"      
[34] "prob_symm"         "divergence"        "clark"            
[37] "additive_symm"     "kullback-leibler"  "jeffreys"         
[40] "k_divergence"      "topsoe"            "jensen-shannon"   
[43] "jensen_difference" "taneja"            "kumar-johnson"    
[46] "avg"              </code></pre>
</div>
</div>
</section>
<section id="visualización-de-matrices-de-distancias" class="level2" data-number="2.14">
<h2 data-number="2.14" class="anchored" data-anchor-id="visualización-de-matrices-de-distancias"><span class="header-section-number">2.14</span> Visualización de matrices de distancias</h2>
<p>Una solución sencilla para visualizar las matrices de distancia es utilizar la función <code>fviz_dist()</code> de la librería <code>factoextra</code>. Otros métodos especializados, como la agrupación jerárquica aglomerativa o el mapa de calor, las presentaremos más adelante.</p>
<p><span style="color: blue;"><em>Ejemplo</em></span>: Visualizamos la tabla de los jugadores de fútbol.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span>
<span id="cb89-2"><a href="#cb89-2" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_dist</span>(<span class="fu">as.dist</span>(distancia))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="EM_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Si el color es rojo, la similitud es alta (es decir, distancia cero). Si el color es azul, la similitud es baja. El nivel de color es proporcional al valor de la distancia entre las observaciones. Se han ordenado a los jugadores por similitud.</p>
<p><span style="color: blue;"><em>Ejemplo</em></span>: Otro ejemplo que podéis consultar son los mapas de calor que utilizamos en BIOCOM (grupo de investigación de la UIB en Biología Computacional y Bioinformática) para presentar las diferencias entre kernels (“distancias”) para comparar grafos del metabolismo entre organismos <a href="https://journals.plos.org/plosone/article/figure?id=10.1371/journal.pone.0281047.g003">Figura 3 - Exploring the expressiveness of abstract metabolic networks</a></p>
<p>Observamos una buena separación entre animales, plantas y hongos en todos los mapas de calor. Los protistas están separados, pero en general están más cerca de los hongos que del resto de Eucariotas. Además, en todos los mapas de calor, los animales están bien separados de los demás reinos y muestran un patrón interno adicional que merece un análisis más detallado. También cabe destacar que todos los kernels ponen de manifiesto una marcada diferencia entre los animales y las plantas. Las plantas están más cerca de los hongos que de los animales.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./intro.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introducción al Análisis de Datos</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./Inferencia.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Inferencia multivariante en poblaciones normales</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Análisis de Datos UIB</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">Este libro se ha creado con <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>



</body></html>